'use strict';

function hex(h, s, l) {
  s /= 100;
  l /= 100;
  const k = (n) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, 9 - k(n), 1));
  return `#${[f(0), f(8), f(4)].map((v) => Math.round(255 * v).toString(16).padStart(2, '0')).join('')}`;
}

function colors(num) {
  const hue = (num * 47) % 360;
  const dark = num % 4 === 0 || num % 7 === 0;
  return dark
    ? { bg: hex(hue, 30, 10), card: hex(hue, 25, 17), accent: hex((hue + 34) % 360, 72, 60), text: '#f7f7f5' }
    : { bg: hex(hue, 35, 96), card: hex(hue, 30, 90), accent: hex((hue + 18) % 360, 58, 40), text: hex(hue, 28, 18) };
}

function spec(num, id, niche, name, emoji, group, title, tagline, page2, usps, p1, p2, p3, keywords, imgTheme) {
  return {
    num, id, niche, name, emoji, group, title, tagline,
    page2,
    usps,
    p1,
    p2,
    p3,
    keywords,
    colors: colors(num),
    imgTheme,
  };
}

module.exports = [
  spec(301, 'closetcraft', 'wardrobe', 'ClosetCraft', '🚪', 'Home Improvement', 'Custom Closet & Walk-in Wardrobes', 'Bespoke modular wardrobes and walk-in closets', { file: 'catalog', label: 'Catalog' }, ['Free 3D Design', 'Premium Fittings', 'Custom Sizes'], 'Hero showcases fitted wardrobes, walk-ins, space-saving storage and a free 3D-design CTA.', 'Catalog compares sliding, hinged, walk-in and loft systems with finishes, fittings and project galleries.', 'Consultation page captures room size, style, budget and location for an on-site measurement visit.', 'wardrobe closet modular walk-in storage cupboard sliding fitted bedroom organizer', 'modular wardrobe closet interior'),
  spec(302, 'roofgreen', 'roofgarden', 'RoofGreen', '🌿', 'Home Improvement', 'Rooftop Garden Design & Maintenance', 'Turn unused terraces into thriving green retreats', { file: 'gardens', label: 'Gardens' }, ['Leak-safe Systems', 'Native Plants', 'AMC Care'], 'Hero presents terrace transformations, heat reduction, waterproof planning and a site-survey CTA.', 'Gardens page covers lawns, planters, kitchen gardens, pergolas and irrigation with before-after projects.', 'Survey form collects terrace area, sunlight, access, city and maintenance preference for a proposal.', 'rooftop terrace garden landscaping plants irrigation pergola waterproof urban green', 'lush rooftop terrace garden'),
  spec(303, 'safetygrill', 'safetygrills', 'SafetyGrill', '🛡️', 'Home Improvement', 'Invisible Grills & Child Safety Nets', 'Secure balconies and windows without blocking the view', { file: 'systems', label: 'Systems' }, ['316-grade Steel', 'Child-safe Spacing', 'Warranty Included'], 'Hero emphasizes unobstructed views, child and pet safety, corrosion resistance and free measurement.', 'Systems page details invisible grills, staircase cables, window guards and installation specifications.', 'Quote page requests opening dimensions, floor, property type and photos for measurement scheduling.', 'invisible grill balcony safety child net window stainless steel cable protection', 'modern balcony invisible safety grill'),
  spec(304, 'smarthomeui', 'homeautomation', 'SmartHomeUI', '📱', 'Home Improvement', 'Smart Home Automation & Control', 'Control lighting, security and comfort from one interface', { file: 'solutions', label: 'Solutions' }, ['App + Voice Control', 'Retrofit Options', 'Remote Support'], 'Hero demonstrates one-touch scenes for lights, curtains, climate and security with a demo CTA.', 'Solutions page groups automation by room and shows compatible sensors, hubs, locks and assistants.', 'Consultation captures property size, construction stage, preferred ecosystem and automation priorities.', 'smart home automation lighting security curtains voice control sensors retrofit app', 'smart home control panel in luxury living room'),
  spec(305, 'floorwood', 'woodflooring', 'FloorWood', '🪵', 'Home Improvement', 'Hardwood & Engineered Wood Flooring', 'Warm, durable wood floors professionally installed', { file: 'floors', label: 'Floors' }, ['Moisture Testing', 'Expert Installation', 'Finish Warranty'], 'Hero highlights natural wood warmth, precision installation and an in-home sample appointment.', 'Floors page compares hardwood, engineered, laminate and parquet by shade, grade and room suitability.', 'Estimate form gathers area, subfloor, preferred tone, occupancy and installation timeline.', 'wood flooring hardwood engineered laminate parquet installation floor polish interior', 'premium oak wood flooring interior'),
  spec(306, 'wallcover', 'wallcoverings', 'WallCover', '🎨', 'Home Improvement', 'Wallpaper & Designer Wall Coverings', 'Statement walls with curated textures and patterns', { file: 'collections', label: 'Collections' }, ['Curated Imports', 'Clean Installation', 'Sample Service'], 'Hero features dramatic wall transformations, washable materials and a sample-book visit CTA.', 'Collections page filters floral, geometric, kids, textured, mural and commercial coverings.', 'Booking page asks wall dimensions, room type, style, city and installation requirement.', 'wallpaper wall covering mural texture pattern interior decor installation feature wall', 'designer wallpaper feature wall'),
  spec(307, 'pigeonnet', 'birdnetting', 'PigeonNet', '🕊️', 'Home Improvement', 'Pigeon Nets & Bird Control', 'Humane, durable protection for balconies and buildings', { file: 'services', label: 'Services' }, ['UV-stable Nets', 'Humane Control', 'Same-day Service'], 'Hero addresses droppings, nesting and balcony safety with rapid inspection and installation.', 'Services page covers balcony nets, duct covers, spikes and commercial façade bird-control work.', 'Booking captures balcony count, approximate size, floor, locality and preferred visit slot.', 'pigeon net bird control balcony netting spikes humane protection installation apartment', 'pigeon protection net on apartment balcony'),
  spec(308, 'washexterior', 'pressurewashing', 'WashExterior', '💦', 'Home Improvement', 'Exterior Pressure Washing', 'Restore façades, driveways and outdoor surfaces', { file: 'services', label: 'Services' }, ['Surface-safe Pressure', 'Eco Detergents', 'Commercial Equipment'], 'Hero contrasts stained and restored exteriors and offers a photo-based instant estimate.', 'Services page lists façade, driveway, deck, paver, roof and commercial pressure cleaning.', 'Quote page collects surface type, area, stain severity, water access and site photographs.', 'pressure washing exterior cleaning facade driveway paver deck roof stain restoration', 'pressure washing building exterior'),
  spec(309, 'crystalclean', 'chandeliercleaning', 'CrystalClean', '✨', 'Home Improvement', 'Chandelier Cleaning & Restoration', 'Meticulous care for crystal and designer lighting', { file: 'care', label: 'Care Plans' }, ['Trained Technicians', 'Insured Handling', 'Crystal-safe Products'], 'Hero focuses on delicate on-site cleaning, sparkle restoration and insured specialist handling.', 'Care Plans explains cleaning, dismantling, rewiring coordination and annual maintenance options.', 'Assessment form requests fixture type, height, crystal count estimate, access and photos.', 'chandelier cleaning crystal restoration lighting fixture rewiring maintenance luxury home', 'sparkling crystal chandelier closeup'),
  spec(310, 'marbleglow', 'marblepolishing', 'MarbleGlow', '💎', 'Home Improvement', 'Marble Polishing & Stone Restoration', 'Bring back the mirror finish of natural stone', { file: 'finishes', label: 'Finishes' }, ['Dust-controlled Process', 'Stain Treatment', 'Long-lasting Seal'], 'Hero shows dull-to-gloss marble restoration, stain removal and a floor inspection CTA.', 'Finishes page explains grinding, honing, polishing, crystallization and sealing for major stones.', 'Estimate page gathers stone type, area, damage, property status and preferred service date.', 'marble polishing stone restoration granite terrazzo crystallization sealing floor shine stains', 'mirror polished marble floor'),
  spec(311, 'movierecliner', 'homerecliners', 'MovieRecliner', '🎬', 'Home Improvement', 'Home Theatre Recliners & Seating', 'Cinema comfort tailored to your room', { file: 'seating', label: 'Seating' }, ['Motorized Comfort', 'Custom Upholstery', 'Room Planning'], 'Hero presents motorized cinema seating, cupholders, console options and room-layout assistance.', 'Seating page compares single, loveseat, row and sectional recliners with fabrics and mechanisms.', 'Planning form captures room dimensions, seat count, upholstery, features and delivery city.', 'home theatre recliner cinema seating motorized leather upholstery media room furniture', 'luxury home cinema recliner seats'),
  spec(312, 'stonecounter', 'stonecountertops', 'StoneCounter', '🪨', 'Home Improvement', 'Granite, Quartz & Stone Countertops', 'Precision-cut surfaces for kitchens and vanities', { file: 'stones', label: 'Stone Gallery' }, ['Laser Measurement', 'Factory Finish', 'Expert Fitting'], 'Hero promotes durable custom countertops, precise fabrication and a home-measurement CTA.', 'Stone Gallery compares granite, quartz, marble and solid surfaces by color, edge and application.', 'Quote page requests layout, dimensions, sink/hob cutouts, preferred stone and project stage.', 'countertop granite quartz marble kitchen vanity stone fabrication installation slab edge', 'quartz kitchen countertop showroom'),
  spec(313, 'balconyturf', 'balconyturfing', 'BalconyTurf', '🌱', 'Home Improvement', 'Artificial Grass for Balconies & Terraces', 'Low-maintenance greenery for compact outdoor spaces', { file: 'turf', label: 'Turf Range' }, ['UV Resistant', 'Fast Drainage', 'Neat Edge Finish'], 'Hero shows instant green balcony makeovers with child-safe, pet-friendly turf options.', 'Turf Range compares pile heights, softness, drainage and use cases with installation examples.', 'Measurement form captures area, surface, drainage, pet use, floor and locality.', 'artificial grass balcony turf terrace lawn synthetic pet friendly drainage installation', 'green artificial turf balcony makeover'),
  spec(314, 'ironcraft', 'ornamentaliron', 'IronCraft', '⚒️', 'Home Improvement', 'Custom Wrought Iron Gates & Railings', 'Hand-finished metalwork built for beauty and security', { file: 'designs', label: 'Designs' }, ['Custom Fabrication', 'Anti-rust Finish', 'On-site Installation'], 'Hero displays bespoke gates, railings and grills with craftsmanship and security messaging.', 'Designs page organizes modern, classic, floral and geometric metalwork with finish options.', 'Quote page requests measurements, application, style reference, automation need and site location.', 'wrought iron gate railing grill metal fabrication custom design powder coating security', 'ornate wrought iron entrance gate'),
  spec(315, 'leakdetect', 'leakdetection', 'LeakDetect', '🔍', 'Home Improvement', 'Non-destructive Water Leak Detection', 'Pinpoint hidden leaks before they cause major damage', { file: 'methods', label: 'Methods' }, ['Thermal Imaging', 'Acoustic Detection', 'Minimal Breakage'], 'Hero highlights accurate hidden-leak diagnosis using instruments rather than guesswork.', 'Methods page explains thermal, acoustic, pressure and moisture testing for homes and facilities.', 'Emergency form captures symptoms, affected rooms, property type, urgency and contact location.', 'water leak detection thermal imaging acoustic plumbing moisture pressure non destructive repair', 'technician using thermal camera for leak'),
  spec(316, 'windowfix', 'windowrepair', 'WindowFix', '🪟', 'Home Improvement', 'Home Window & Sliding Door Repair', 'Smooth movement, tight seals and safer locking', { file: 'repairs', label: 'Repairs' }, ['All Major Profiles', 'Genuine Hardware', 'On-site Service'], 'Hero targets jammed sliders, broken rollers, gaps and lock issues with doorstep repairs.', 'Repairs page lists rollers, channels, handles, locks, mesh, glass and weather-seal services.', 'Booking form captures window type, fault, quantity, profile brand, location and photos.', 'window repair sliding door roller lock handle mesh glass seal aluminium upvc', 'technician repairing sliding window'),
  spec(317, 'mirrorwall', 'decorativemirrors', 'MirrorWall', '🪞', 'Home Improvement', 'Custom Mirrors & Mirror Walls', 'Made-to-measure reflections for brighter interiors', { file: 'styles', label: 'Styles' }, ['Custom Cutting', 'Safety Backing', 'Clean Installation'], 'Hero showcases full-wall, bevelled and decorative mirrors that expand and brighten rooms.', 'Styles page presents gym, wardrobe, vanity, antique and geometric mirror installations.', 'Quote form asks dimensions, edge style, tint, cutouts, wall condition and installation city.', 'custom mirror wall bevelled vanity gym antique decorative glass installation interior', 'geometric decorative mirror wall'),
  spec(318, 'fireplacecare', 'chimneycare', 'FireplaceCare', '🔥', 'Home Improvement', 'Fireplace & Chimney Cleaning', 'Safer fires through professional inspection and sweeping', { file: 'care', label: 'Care Plans' }, ['Soot Removal', 'Safety Inspection', 'Mess-free Service'], 'Hero stresses chimney safety, cleaner burning and seasonal inspection with easy booking.', 'Care Plans covers sweeping, flue inspection, nest removal, cap checks and annual servicing.', 'Booking collects fireplace type, last service, symptoms, storeys and preferred appointment.', 'fireplace chimney cleaning sweeping soot flue inspection safety maintenance cap smoke', 'professional chimney sweeping fireplace'),
  spec(319, 'tankclean', 'watertankcleaning', 'TankClean', '🧼', 'Home Improvement', 'Water Tank Cleaning & Sanitization', 'Multi-step hygienic cleaning for safer stored water', { file: 'process', label: 'Process' }, ['Mechanized Cleaning', 'Food-grade Disinfection', 'Service Report'], 'Hero explains hygienic overhead and underground tank cleaning with visible process assurance.', 'Process page details dewatering, sludge removal, scrubbing, pressure wash, disinfection and UV treatment.', 'Booking captures tank type, capacity, count, access, property and desired service slot.', 'water tank cleaning sanitization overhead underground disinfection sludge pressure wash hygiene', 'water tank professional cleaning service'),
  spec(320, 'doorfit', 'doorinstallation', 'DoorFit', '🚪', 'Home Improvement', 'Door Installation & Hardware Fitting', 'Precisely fitted doors, locks and architectural hardware', { file: 'doors', label: 'Door Range' }, ['Accurate Alignment', 'Premium Hardware', 'Clean Handover'], 'Hero covers new-door fitting, replacement and hardware upgrades with site measurement.', 'Door Range compares flush, veneer, laminate, glass and security doors plus lock options.', 'Estimate form requests opening size, door count, material, hardware and project location.', 'door installation fitting lock hinge hardware flush veneer security replacement carpenter', 'carpenter fitting premium wooden door'),

  spec(321, 'bookbind', 'bookbinding', 'BookBind', '📚', 'Craft & Artisan', 'Hand Bookbinding & Restoration', 'Books, journals and heirlooms bound by hand', { file: 'bindings', label: 'Bindings' }, ['Archival Materials', 'Hand Sewn', 'Custom Personalization'], 'Hero celebrates handmade journals, thesis binding and sensitive restoration with commission CTA.', 'Bindings page covers leather, cloth, case, exposed-spine and restoration work with options.', 'Commission form captures book type, quantity, dimensions, material, personalization and deadline.', 'bookbinding journal restoration leather archival thesis handmade notebook embossing craft', 'artisan hand binding leather book'),
  spec(322, 'stainedglass', 'stainedglasswork', 'StainedGlass', '🌈', 'Craft & Artisan', 'Custom Stained Glass Art', 'Light-filled panels handcrafted for distinctive spaces', { file: 'gallery', label: 'Gallery' }, ['Original Designs', 'Traditional Leadwork', 'Secure Shipping'], 'Hero shows luminous windows and panels, custom design expertise and commission booking.', 'Gallery presents floral, geometric, religious and contemporary panels, lamps and restorations.', 'Commission page gathers dimensions, colors, subject, installation setting, budget and timeline.', 'stained glass custom window panel leadwork restoration lamp art commission handmade', 'colorful stained glass window sunlight'),
  spec(323, 'epoxycraft', 'epoxyart', 'EpoxyCraft', '🌀', 'Craft & Artisan', 'Epoxy Resin Art & Furniture', 'One-of-a-kind resin pieces poured by hand', { file: 'collection', label: 'Collection' }, ['Food-safe Options', 'Custom Pigments', 'Made to Order'], 'Hero features river tables, wall art and keepsakes with dramatic resin details.', 'Collection page lists tables, trays, clocks, coasters and preservation pieces by finish.', 'Order form collects product, size, color palette, embedded items, shipping city and deadline.', 'epoxy resin art river table furniture coaster tray preservation custom pigment handmade', 'blue epoxy resin river table'),
  spec(324, 'puppetcraft', 'puppetmaking', 'PuppetCraft', '🎭', 'Craft & Artisan', 'Handmade Puppets & Puppet Shows', 'Characters crafted for stories, learning and performance', { file: 'puppets', label: 'Puppets' }, ['Original Characters', 'Child-safe Materials', 'Show Bookings'], 'Hero combines handcrafted puppet sales, educational storytelling and live-show booking.', 'Puppets page features string, hand, rod and custom mascot puppets plus show themes.', 'Enquiry captures puppet or show need, audience age, character brief, quantity, venue and date.', 'puppet handmade marionette storytelling show educational children mascot theatre craft', 'colorful handmade puppets workshop'),
  spec(325, 'neonartistry', 'neonsigns', 'NeonArtistry', '💡', 'Craft & Artisan', 'Custom Neon Signs & Light Art', 'Turn names, logos and ideas into glowing statements', { file: 'designs', label: 'Designs' }, ['Free Mockup', 'Low-energy LED', 'Dimmable Options'], 'Hero showcases custom neon names, logos and décor with a free design mockup CTA.', 'Designs page covers wedding, home, business, event and artwork signs with sizes and colors.', 'Custom quote asks text/logo, dimensions, color, backing, indoor/outdoor use and deadline.', 'custom neon sign led light art logo wedding name wall decor dimmable', 'custom pink neon sign on dark wall'),
  spec(326, 'terrariumcraft', 'terrariums', 'TerrariumCraft', '🌵', 'Craft & Artisan', 'Terrariums & Miniature Gardens', 'Self-contained green worlds made with care', { file: 'gardens', label: 'Gardens' }, ['Live Plants', 'Care Guide', 'Gift Packaging'], 'Hero features open and closed terrariums, workshops and personalized green gifts.', 'Gardens page displays desktop, hanging, themed and corporate terrariums by size.', 'Order page captures style, size, occasion, personalization, delivery city and workshop interest.', 'terrarium miniature garden plants moss succulent glass gift workshop indoor green', 'lush miniature terrarium in glass'),
  spec(327, 'woodtoys', 'woodentoys', 'WoodToys', '🧸', 'Craft & Artisan', 'Handcrafted Wooden Toys', 'Durable, imaginative play made from natural wood', { file: 'toys', label: 'Toy Shop' }, ['Non-toxic Finish', 'Rounded Edges', 'Personalized Names'], 'Hero promotes heirloom-quality, screen-free play and safe natural materials.', 'Toy Shop groups pull toys, puzzles, vehicles, pretend play and personalized keepsakes by age.', 'Order enquiry records toy, child age, personalization, quantity, gifting date and delivery city.', 'wooden toys handmade child safe puzzle montessori natural wood personalized learning play', 'handcrafted colorful wooden toys'),
  spec(328, 'claypottery', 'ceramicpottery', 'ClayPottery', '🏺', 'Craft & Artisan', 'Studio Pottery & Ceramic Workshops', 'Wheel-thrown ceramics for everyday rituals', { file: 'ceramics', label: 'Ceramics' }, ['Hand Thrown', 'Food-safe Glazes', 'Workshop Sessions'], 'Hero introduces functional ceramics, one-off collections and hands-on pottery classes.', 'Ceramics page presents mugs, tableware, planters, décor and workshop schedules.', 'Booking form covers product order or class, quantity, glaze, participants, date and delivery.', 'pottery ceramic clay wheel thrown mug tableware glaze workshop handmade planter', 'potter shaping clay on wheel'),
  spec(329, 'invitecraft', 'invitationdesign', 'InviteCraft', '💌', 'Craft & Artisan', 'Bespoke Wedding Invitations', 'Thoughtful stationery that begins your celebration', { file: 'suites', label: 'Suites' }, ['Custom Illustration', 'Premium Papers', 'Coordinated Stationery'], 'Hero presents luxury invitation suites, cultural motifs and custom illustration services.', 'Suites page compares digital, printed, boxed and eco-friendly invitations with add-ons.', 'Design brief captures event, quantity, language, theme, functions, budget and delivery date.', 'wedding invitation bespoke stationery card digital invite print box illustration calligraphy', 'luxury Indian wedding invitation suite'),
  spec(330, 'bladecraft', 'customknives', 'BladeCraft', '🔪', 'Craft & Artisan', 'Hand-Forged Knives & Blades', 'Purpose-built blades forged, ground and finished by hand', { file: 'blades', label: 'Blades' }, ['Hand Forged', 'Heat Treated', 'Custom Handles'], 'Hero highlights chef, outdoor and collector knives with responsible craftsmanship.', 'Blades page details steel, geometry, handle materials, sheath options and available pieces.', 'Commission form requests blade purpose, length, steel, handle, engraving and legal confirmation.', 'hand forged knife blade chef outdoor steel custom handle heat treatment sheath', 'artisan forging custom chef knife'),
  spec(331, 'kicksart', 'sneakerrestoration', 'KicksArt', '👟', 'Craft & Artisan', 'Custom Sneaker Art & Restoration', 'Wearable art designed around your story', { file: 'styles', label: 'Styles' }, ['Original Artwork', 'Sealed Finish', 'Restoration Available'], 'Hero displays bold custom sneakers, restorations and a start-your-design CTA.', 'Styles page showcases anime, portrait, minimal, sports and brand-inspired commissions.', 'Brief collects shoe model, size, theme, colors, reference, deadline and shipping city.', 'custom sneakers shoe art painting restoration kicks anime portrait wearable commission', 'hand painted custom sneakers'),
  spec(332, 'rugcraft', 'handmaderugs', 'RugCraft', '🧶', 'Craft & Artisan', 'Custom Tufted Rugs & Textile Art', 'Soft statement pieces shaped to your imagination', { file: 'rugs', label: 'Rugs' }, ['Custom Shapes', 'Dense Tufting', 'Color Matching'], 'Hero features sculptural tufted rugs, wall hangings and logo pieces.', 'Rugs page displays abstract, character, logo and décor commissions by size and pile.', 'Quote form asks shape, dimensions, artwork, palette, floor/wall use and delivery date.', 'custom rug tufted carpet textile art handmade logo wall hanging decor yarn', 'colorful hand tufted rug'),
  spec(333, 'soundinstruments', 'instrumentmaking', 'SoundInstruments', '🎸', 'Craft & Artisan', 'Handmade Musical Instruments', 'Instruments voiced and finished by skilled makers', { file: 'instruments', label: 'Instruments' }, ['Tonewood Selection', 'Player Setup', 'Repair Support'], 'Hero centers craftsmanship, tone and custom player setup for handmade instruments.', 'Instruments page presents strings, percussion and folk instruments plus available builds.', 'Commission captures instrument, playing style, woods, scale, finish, budget and timeline.', 'handmade musical instrument luthier guitar percussion folk tonewood custom repair craft', 'luthier crafting acoustic instrument'),
  spec(334, 'dioramacraft', 'miniaturedioramas', 'DioramaCraft', '🏘️', 'Craft & Artisan', 'Miniature Models & Dioramas', 'Detailed small worlds for collectors, exhibits and gifts', { file: 'projects', label: 'Projects' }, ['Scale Accuracy', 'Hand-painted Detail', 'Protective Display'], 'Hero showcases architectural, military, fantasy and memory-scene miniatures.', 'Projects page sorts dioramas by theme, scale and purpose with close-up detail galleries.', 'Commission form asks subject, scale, dimensions, reference assets, display case and deadline.', 'diorama miniature model scale architecture collectible scene handmade display commission', 'high detail miniature diorama scene'),
  spec(335, 'pureincense', 'artisanincense', 'PureIncense', '🪔', 'Craft & Artisan', 'Natural Incense & Ritual Fragrances', 'Slow-crafted aromas from botanicals and resins', { file: 'fragrances', label: 'Fragrances' }, ['Natural Ingredients', 'Charcoal-free Options', 'Small Batch'], 'Hero communicates pure ingredients, mindful rituals and signature fragrance blends.', 'Fragrances page covers sticks, cones, dhoop, resins and gift sets with scent notes.', 'Order page supports fragrance selection, quantity, gifting, wholesale enquiry and delivery.', 'natural incense agarbatti dhoop resin fragrance ritual botanical charcoal free handmade', 'natural incense sticks and botanicals'),
  spec(336, 'leathersheath', 'leathersheaths', 'LeatherSheath', '🧵', 'Craft & Artisan', 'Custom Leather Sheaths & Holsters', 'Protective leatherwork fitted to your tools', { file: 'leather', label: 'Leatherwork' }, ['Hand Stitched', 'Wet Molded Fit', 'Personalized Stamping'], 'Hero presents fitted knife sheaths, tool holders and field-ready leatherwork.', 'Leatherwork page explains carry styles, hides, stitching, hardware and personalization.', 'Commission asks item dimensions, carry orientation, leather color, tooling and shipping.', 'leather sheath holster knife tool holder hand stitched custom molded carving', 'hand stitched leather knife sheath'),
  spec(337, 'woodboards', 'servingboards', 'WoodBoards', '🧀', 'Craft & Artisan', 'Handmade Cutting & Serving Boards', 'Solid-wood boards made for kitchens and celebrations', { file: 'boards', label: 'Boards' }, ['Food-safe Finish', 'Solid Hardwood', 'Name Engraving'], 'Hero features cutting, charcuterie and presentation boards with personalization.', 'Boards page compares woods, grain patterns, shapes, juice grooves and gift sets.', 'Order form requests board type, size, wood, engraving, quantity and delivery date.', 'cutting board serving charcuterie wood handmade kitchen engraving gift hardwood', 'artisan hardwood serving boards'),
  spec(338, 'bespokesuits', 'bespoketailoring', 'BespokeSuits', '🤵', 'Craft & Artisan', 'Bespoke Suits & Formalwear', 'Individually cut tailoring with a precise personal fit', { file: 'tailoring', label: 'Tailoring' }, ['Personal Pattern', 'Premium Fabrics', 'Multiple Fittings'], 'Hero presents made-to-measure suits, craftsmanship and private appointment booking.', 'Tailoring page covers business, wedding, tuxedo and occasion garments plus fabric choices.', 'Appointment form captures occasion, garment, date, city, style and fitting preference.', 'bespoke suit tailoring formalwear tuxedo wedding fabric fitting menswear custom', 'tailor fitting bespoke luxury suit'),
  spec(339, 'quiltcraft', 'quilting', 'QuiltCraft', '🧵', 'Craft & Artisan', 'Custom Quilts & Memory Blankets', 'Stitched keepsakes made from meaningful fabrics', { file: 'quilts', label: 'Quilts' }, ['Memory Fabric Care', 'Custom Patterns', 'Hand Finished'], 'Hero tells the story of heirloom quilts, baby blankets and memory keepsakes.', 'Quilts page presents patchwork, memory, baby and art quilts by style and size.', 'Commission captures quilt type, dimensions, supplied garments, palette and required date.', 'custom quilt memory blanket patchwork baby heirloom sewing textile handmade keepsake', 'colorful handmade patchwork quilt'),
  spec(340, 'fibercraft', 'fiberart', 'FiberCraft', '🪢', 'Craft & Artisan', 'Macramé & Contemporary Fiber Art', 'Textural handmade pieces for homes and events', { file: 'pieces', label: 'Pieces' }, ['Hand Knotted', 'Natural Fibers', 'Custom Sizing'], 'Hero showcases large wall hangings, plant holders and event backdrops.', 'Pieces page groups décor, lighting, planters, wedding backdrops and wearable fiber art.', 'Order brief requests item, dimensions, colors, mounting, event date and delivery city.', 'macrame fiber art wall hanging knot decor plant holder wedding backdrop handmade', 'large bohemian macrame wall hanging'),

  spec(341, 'crossborder', 'crossbordercommerce', 'CrossBorder', '🌍', 'Global Enterprise', 'Cross-border E-commerce Enablement', 'Launch, localize and scale products across global marketplaces', { file: 'markets', label: 'Markets' }, ['Marketplace Setup', 'Duty Guidance', 'Localized Growth'], 'Hero positions an end-to-end partner for international marketplace expansion and compliance.', 'Markets page maps launch services across Amazon, eBay, regional channels and D2C storefronts.', 'Strategy call gathers products, origin, target countries, current revenue and logistics setup.', 'cross border ecommerce global marketplace export localization customs duty amazon international', 'global ecommerce logistics network'),
  spec(342, 'offshoredev', 'offshoreengineering', 'OffshoreDev', '💻', 'Global Enterprise', 'Offshore Software Development Teams', 'Dedicated engineering capacity aligned to your roadmap', { file: 'expertise', label: 'Expertise' }, ['Vetted Engineers', 'Agile Delivery', 'IP Protection'], 'Hero offers dedicated product teams, transparent delivery and rapid technical discovery.', 'Expertise page covers web, mobile, cloud, data, QA and DevOps with engagement models.', 'Discovery form captures stack, roles, team size, overlap hours, timeline and security needs.', 'offshore software development dedicated team engineers agile web mobile cloud devops', 'distributed software engineering team'),
  spec(343, 'exporttrade', 'exportconsulting', 'ExportTrade', '🚢', 'Global Enterprise', 'Export Documentation & Trade Advisory', 'Navigate international trade with compliant documentation', { file: 'services', label: 'Services' }, ['Document Accuracy', 'Market Guidance', 'Shipment Support'], 'Hero focuses on export readiness, documentation and smooth shipment coordination.', 'Services page covers IEC guidance, invoices, certificates, customs, incentives and market entry.', 'Consultation collects product, HS code if known, origin, destination, volume and shipment stage.', 'export documentation trade consulting customs shipping certificate invoice compliance international', 'cargo containers international port trade'),
  spec(344, 'privatelabel', 'privatelabelsourcing', 'PrivateLabel', '🏷️', 'Global Enterprise', 'Private-label Product Sourcing', 'Source, customize and launch products under your brand', { file: 'categories', label: 'Categories' }, ['Verified Factories', 'Sample Management', 'Quality Checks'], 'Hero promises supplier discovery, customization and production oversight from brief to dispatch.', 'Categories page presents sourcing sectors, MOQ guidance, packaging and case studies.', 'Brief captures product, target cost, quantity, customization, certifications and market.', 'private label sourcing manufacturer supplier oem packaging quality inspection product launch', 'private label product packaging factory'),
  spec(345, 'virtualbpo', 'virtualoperations', 'VirtualBPO', '🎧', 'Global Enterprise', 'Virtual BPO & Back-office Operations', 'Flexible trained teams for customer and business operations', { file: 'operations', label: 'Operations' }, ['24/7 Coverage', 'SLA Reporting', 'Scalable Seats'], 'Hero positions scalable voice, chat and back-office delivery with measurable SLAs.', 'Operations page details support, data processing, finance ops, moderation and virtual assistance.', 'Scope form captures process, channels, languages, seat count, hours and compliance needs.', 'virtual bpo back office customer support call center data processing outsourcing operations', 'modern customer support operations team'),
  spec(346, 'carbonneutral', 'carbonadvisory', 'CarbonNeutral', '♻️', 'Global Enterprise', 'Carbon Accounting & Net-zero Advisory', 'Measure emissions and build a credible decarbonization plan', { file: 'pathway', label: 'Net-zero Pathway' }, ['GHG-aligned', 'Audit-ready Data', 'Practical Roadmap'], 'Hero frames emissions measurement, target setting and transparent climate action.', 'Pathway page explains scopes 1–3, inventories, reduction plans, disclosures and offsets.', 'Assessment gathers industry, locations, energy data, reporting boundary and target year.', 'carbon accounting net zero emissions sustainability ghg scope esg climate reporting', 'business sustainability carbon dashboard'),
  spec(347, 'dronesurvey', 'aerialsurveying', 'DroneSurvey', '🚁', 'Global Enterprise', 'Drone Mapping & Industrial Surveys', 'Fast, accurate aerial data for better field decisions', { file: 'applications', label: 'Applications' }, ['Licensed Pilots', 'Survey-grade Outputs', 'Rapid Turnaround'], 'Hero demonstrates orthomosaics, inspections and volumetrics captured safely from the air.', 'Applications page covers construction, solar, mining, agriculture and infrastructure deliverables.', 'Mission brief records site, area, coordinates, output, accuracy, permissions and schedule.', 'drone survey aerial mapping inspection photogrammetry construction mining solar volumetric gis', 'survey drone flying over industrial site'),
  spec(348, 'polyglot', 'businesslocalization', 'PolyGlot', '🗣️', 'Global Enterprise', 'Business Translation & Localization', 'Make products and communication feel native in every market', { file: 'languages', label: 'Languages' }, ['Native Linguists', 'Terminology Control', 'QA Workflow'], 'Hero promotes human-led translation, product localization and multilingual consistency.', 'Languages page maps supported language pairs and content types with industry expertise.', 'Quote form captures languages, word count, file types, subject, certification and deadline.', 'translation localization multilingual native linguist website software document language qa', 'multilingual business localization workspace'),
  spec(349, 'isoquality', 'isocertification', 'ISOQuality', '✅', 'Global Enterprise', 'ISO Certification Consulting', 'Build practical management systems ready for certification', { file: 'standards', label: 'Standards' }, ['Gap Assessment', 'Documentation', 'Audit Readiness'], 'Hero communicates clear certification roadmaps without unnecessary paperwork.', 'Standards page covers ISO 9001, 14001, 27001, 45001 and sector standards.', 'Readiness form captures standard, company size, locations, existing systems and target date.', 'iso certification consulting 9001 27001 14001 audit quality compliance documentation', 'ISO quality audit business meeting'),
  spec(350, 'influencerhub', 'influencermarketing', 'InfluencerHub', '📣', 'Global Enterprise', 'Influencer Marketing Campaigns', 'Creator partnerships planned for reach, relevance and results', { file: 'campaigns', label: 'Campaigns' }, ['Verified Creators', 'Usage Rights', 'Performance Reports'], 'Hero combines creator discovery, campaign execution and measurable brand outcomes.', 'Campaigns page presents launch, UGC, regional and always-on programs with case results.', 'Brief asks product, audience, geography, platforms, creator tier, deliverables and budget.', 'influencer marketing creator campaign ugc brand social media reach engagement performance', 'influencer content production campaign'),
  spec(351, 'botcraft', 'chatbotautomation', 'BotCraft', '🤖', 'Global Enterprise', 'AI Chatbots & Workflow Automation', 'Automate conversations and repetitive work across your stack', { file: 'automations', label: 'Automations' }, ['Custom Knowledge', 'Human Handoff', 'System Integrations'], 'Hero shows AI agents answering, qualifying and completing tasks around the clock.', 'Automations page covers support bots, lead capture, internal copilots and process workflows.', 'Discovery collects use case, channels, knowledge sources, systems, volume and escalation rules.', 'ai chatbot automation workflow agent customer support lead generation integration bot', 'AI chatbot workflow dashboard'),
  spec(352, 'ecommanager', 'marketplaceoperations', 'EcomManager', '🛒', 'Global Enterprise', 'E-commerce Marketplace Management', 'Operate listings, ads and growth from one expert team', { file: 'channels', label: 'Channels' }, ['Catalog Health', 'Ad Optimization', 'Weekly Reporting'], 'Hero positions full-account operations for brands seeking profitable marketplace growth.', 'Channels page covers Amazon, Flipkart, Meesho and D2C tasks from catalog to ads.', 'Audit form requests channels, SKUs, monthly sales, ad spend, challenges and access readiness.', 'ecommerce marketplace management amazon flipkart listings ads catalog operations sales', 'ecommerce marketplace analytics dashboard'),
  spec(353, '3drenderstudio', 'architecturalrendering', '3DRenderStudio', '🏙️', 'Global Enterprise', '3D Architectural Rendering Studio', 'Photoreal visuals that sell spaces before they exist', { file: 'portfolio', label: 'Portfolio' }, ['Photoreal Detail', 'Design Collaboration', 'VR-ready Options'], 'Hero uses cinematic exterior and interior renders with a project-start CTA.', 'Portfolio filters residential, commercial, product, animation and virtual-tour work.', 'Brief captures drawings, model availability, views, resolution, style, revisions and deadline.', '3d rendering architectural visualization interior exterior animation vr photoreal studio', 'photoreal architectural exterior rendering'),
  spec(354, 'ipbroker', 'ipcommercialization', 'IPBroker', '💡', 'Global Enterprise', 'Patent & Intellectual Property Brokerage', 'Connect valuable IP with buyers, licensees and partners', { file: 'opportunities', label: 'Opportunities' }, ['Confidential Process', 'Market Mapping', 'Deal Support'], 'Hero targets patent owners and strategic buyers with discreet commercialization support.', 'Opportunities page explains sell-side, licensing, valuation coordination and buyer searches.', 'Confidential enquiry gathers asset type, jurisdiction, status, sector and transaction goal.', 'patent broker intellectual property licensing commercialization valuation buyer technology transfer', 'patent documents innovation business deal'),
  spec(355, 'corporatefit', 'corporatewellness', 'CorporateFit', '🏃', 'Global Enterprise', 'Corporate Fitness & Wellness Programs', 'Healthier teams through engaging workplace wellbeing', { file: 'programs', label: 'Programs' }, ['Hybrid Delivery', 'Participation Analytics', 'Certified Coaches'], 'Hero links employee energy, engagement and sustainable wellbeing to flexible programs.', 'Programs page covers fitness, yoga, nutrition, challenges, ergonomics and health events.', 'Proposal form captures workforce, locations, mode, objectives, frequency and budget.', 'corporate wellness employee fitness yoga nutrition workplace health challenge engagement', 'corporate team fitness wellness session'),
  spec(356, 'franchisegrow', 'franchiseconsulting', 'FranchiseGrow', '📈', 'Global Enterprise', 'Franchise Development & Expansion', 'Turn proven businesses into scalable franchise systems', { file: 'roadmap', label: 'Roadmap' }, ['Model Design', 'Documentation', 'Partner Recruitment'], 'Hero offers franchise readiness, model creation and network growth support.', 'Roadmap page covers feasibility, financial model, manuals, legal coordination and sales.', 'Assessment captures business age, outlets, economics, target regions and expansion goals.', 'franchise consulting development expansion model manual partner recruitment business scale', 'franchise business expansion planning'),
  spec(357, 'telesales', 'outsourcedsales', 'TeleSales', '☎️', 'Global Enterprise', 'Outsourced Telesales & Lead Qualification', 'Trained sales teams that turn conversations into pipeline', { file: 'solutions', label: 'Solutions' }, ['Recorded Calls', 'CRM Updates', 'Conversion Reporting'], 'Hero focuses on qualified meetings, consistent outreach and transparent campaign reporting.', 'Solutions page details lead qualification, appointment setting, renewals and inside sales.', 'Campaign brief gathers offer, audience, lead source, geography, language, volume and target.', 'telesales outsourced sales lead qualification appointment setting call campaign crm conversion', 'professional inside sales call team'),
  spec(358, 'tickethub', 'ticketingplatform', 'TicketHub', '🎟️', 'Global Enterprise', 'Event Ticketing & Access Management', 'Sell tickets and manage entry without operational friction', { file: 'features', label: 'Features' }, ['Instant QR Tickets', 'Live Sales Dashboard', 'Fast Check-in'], 'Hero presents branded ticket sales, secure payments and rapid QR entry.', 'Features page covers event pages, ticket tiers, coupons, scanning, payouts and attendee exports.', 'Organizer form collects event, date, venue, capacity, pricing and expected launch.', 'event ticketing qr tickets booking check in organizer payments attendee access platform', 'mobile event ticket QR scanning'),
  spec(359, 'adfilmstudio', 'commercialfilms', 'AdFilmStudio', '🎥', 'Global Enterprise', 'Advertising Film Production', 'Brand stories developed from concept through final cut', { file: 'work', label: 'Our Work' }, ['Concept to Delivery', 'Production Crew', 'Multi-format Masters'], 'Hero leads with a showreel and integrated creative-production capability.', 'Our Work organizes commercials, digital films, product videos and branded content.', 'Production brief captures brand, objective, audience, formats, locations, budget and deadline.', 'advertising film production commercial video brand content director post production campaign', 'advertising film production set'),
  spec(360, 'erpimplement', 'erpconsulting', 'ERPImplement', '⚙️', 'Global Enterprise', 'ERP Implementation & Integration', 'Unify operations with systems configured around your business', { file: 'platforms', label: 'Platforms' }, ['Process Mapping', 'Data Migration', 'User Training'], 'Hero promises controlled ERP transformation from process discovery through adoption.', 'Platforms page covers ERP suites, modules, integrations, migration and managed support.', 'Discovery captures industry, users, locations, current systems, modules and go-live target.', 'erp implementation integration data migration process mapping finance inventory crm training', 'enterprise ERP implementation dashboard'),

  spec(361, 'speedkart', 'kartingtrack', 'SpeedKart', '🏎️', 'Sports & Recreation', 'Go-kart Racing Track', 'Fast laps, safe racing and unforgettable group events', { file: 'races', label: 'Race Packages' }, ['Timed Laps', 'Safety Gear', 'Group Events'], 'Hero delivers high-energy track action, pricing cues and a book-your-race CTA.', 'Race Packages covers arrive-and-drive, kids, groups, birthdays and corporate championships.', 'Booking collects racers, ages, date, slot, package and celebration requirements.', 'go kart racing track speed laps group birthday corporate motorsport booking', 'go kart racing action on track'),
  spec(362, 'targetshoot', 'shootingacademy', 'TargetShoot', '🎯', 'Sports & Recreation', 'Sport Shooting Academy', 'Structured coaching for focus, safety and competition', { file: 'training', label: 'Training' }, ['Certified Coaches', 'Safety First', 'Competition Pathway'], 'Hero introduces supervised rifle and pistol training for beginners and athletes.', 'Training page covers trial sessions, foundation courses, equipment and competition coaching.', 'Enrolment captures age, experience, discipline, goals, city and preferred schedule.', 'sport shooting academy rifle pistol target coaching competition safety training range', 'athlete aiming air rifle target'),
  spec(363, 'royalrider', 'equestrianclub', 'RoyalRider', '🐎', 'Sports & Recreation', 'Horse Riding & Equestrian Club', 'Learn, ride and connect with horses confidently', { file: 'lessons', label: 'Lessons' }, ['Trained Horses', 'Expert Instructors', 'Arena Safety'], 'Hero presents riding lessons, trail experiences and a welcoming equestrian community.', 'Lessons page details beginner, children, dressage, jumping and leisure ride options.', 'Booking form asks rider age, experience, lesson goal, preferred date and group size.', 'horse riding equestrian club lessons arena trail dressage jumping children coaching', 'equestrian rider training in arena'),
  spec(364, 'deepdive', 'scubadiving', 'DeepDive', '🤿', 'Sports & Recreation', 'Scuba Diving School & Trips', 'Train safely and explore the world below the surface', { file: 'dives', label: 'Dive Programs' }, ['Certified Instructors', 'Quality Gear', 'Small Groups'], 'Hero combines underwater adventure, recognized training and beginner discovery dives.', 'Dive Programs covers discovery, certification, specialties, fun dives and travel expeditions.', 'Booking collects certification, experience, swimmers, dates, destination and equipment needs.', 'scuba diving school certification underwater trip instructor gear ocean adventure course', 'scuba diver exploring coral reef'),
  spec(365, 'icerink', 'iceskatingrink', 'IceRink', '⛸️', 'Sports & Recreation', 'Ice Skating Rink & Academy', 'Glide, learn and celebrate on real ice', { file: 'sessions', label: 'Sessions' }, ['Skate Rental', 'Coach-led Lessons', 'Party Packages'], 'Hero promotes public skating, lessons and cool celebrations with session booking.', 'Sessions page lists public slots, beginner classes, figure skating and group packages.', 'Booking captures date, skaters, ages, shoe sizes, lesson need and party add-ons.', 'ice skating rink academy lessons figure skate rental party public session', 'bright indoor ice skating rink'),
  spec(366, 'boulderinghub', 'boulderinggym', 'BoulderingHub', '🧗', 'Sports & Recreation', 'Bouldering & Climbing Gym', 'Creative routes for first climbs and stronger movement', { file: 'climb', label: 'Climb Options' }, ['Reset Routes', 'Safety Induction', 'Community Events'], 'Hero shows dynamic climbing, beginner access and a first-session offer.', 'Climb Options covers day passes, memberships, coaching, kids and competitions.', 'Waiver booking captures climber age, experience, group, date and shoe rental.', 'bouldering climbing gym routes coaching membership kids wall fitness community', 'indoor bouldering climbing wall'),
  spec(367, 'smashbadminton', 'badmintonacademy', 'SmashBadminton', '🏸', 'Sports & Recreation', 'Badminton Academy & Courts', 'Better technique, faster movement and bookable courts', { file: 'coaching', label: 'Coaching' }, ['Professional Courts', 'Skill Batches', 'Match Training'], 'Hero combines academy coaching, court booking and player development.', 'Coaching page details kids, adults, advanced batches, private lessons and court slots.', 'Enquiry gathers age, level, goal, preferred batch, location and trial date.', 'badminton academy court coaching smash kids adult tournament training booking', 'badminton player smashing shuttlecock'),
  spec(368, 'ttacademy', 'tabletennisacademy', 'TTAcademy', '🏓', 'Sports & Recreation', 'Table Tennis Academy', 'Build speed, spin and match intelligence', { file: 'programs', label: 'Programs' }, ['Qualified Coaches', 'Robot Practice', 'Tournament Prep'], 'Hero highlights systematic table-tennis coaching from first rally to competition.', 'Programs page outlines foundation, intermediate, elite, private and open-play sessions.', 'Trial form asks player age, experience, goals, schedule and preferred center.', 'table tennis academy ping pong coaching robot practice tournament kids training', 'table tennis coaching training session'),
  spec(369, 'squashpro', 'squashacademy', 'SquashPro', '🎾', 'Sports & Recreation', 'Squash Coaching & Court Booking', 'Sharper movement, cleaner strokes and competitive play', { file: 'sessions', label: 'Sessions' }, ['Glass Courts', 'Video Feedback', 'League Play'], 'Hero promotes coached sessions, modern courts and convenient booking.', 'Sessions page covers juniors, adults, private coaching, court hire and leagues.', 'Booking gathers level, session type, player count, date and equipment rental.', 'squash coaching court academy junior adult league racquet fitness booking', 'squash player on glass court'),
  spec(370, 'golfsim', 'golfsimulator', 'GolfSim', '⛳', 'Sports & Recreation', 'Indoor Golf Simulator Lounge', 'Play world-class courses, practice and socialize indoors', { file: 'bays', label: 'Bay Packages' }, ['Accurate Tracking', 'Famous Courses', 'Club Rental'], 'Hero presents immersive simulator golf for practice, games and private events.', 'Bay Packages covers hourly play, coaching, leagues, parties and corporate bookings.', 'Reservation collects players, duration, date, skill level, clubs and food needs.', 'golf simulator indoor lounge virtual course swing tracking coaching corporate event', 'premium indoor golf simulator bay'),
  spec(371, 'crossfitbox', 'functionalfitness', 'CrossFitBox', '🏋️', 'Sports & Recreation', 'CrossFit & Functional Fitness Box', 'Coach-led training that makes everyday athletes stronger', { file: 'classes', label: 'Classes' }, ['Small Classes', 'Scalable Workouts', 'Progress Tracking'], 'Hero channels community energy, coached workouts and a free introductory session.', 'Classes page covers fundamentals, daily WODs, strength, conditioning and open gym.', 'Trial form captures fitness level, injuries, goals, preferred time and location.', 'crossfit functional fitness wod strength conditioning coach community classes gym', 'functional fitness group workout'),
  spec(372, 'pilatesstudio', 'reformerpilates', 'PilatesStudio', '🧘', 'Sports & Recreation', 'Reformer Pilates Studio', 'Controlled movement for strength, posture and balance', { file: 'classes', label: 'Classes' }, ['Small Groups', 'Certified Instructors', 'Personal Plans'], 'Hero conveys calm premium reformer sessions and personalized instruction.', 'Classes page compares introductory, group, private, prenatal and rehabilitation-focused sessions.', 'Booking asks experience, goals, health notes, session type and preferred schedule.', 'reformer pilates studio posture core strength private class prenatal mobility', 'calm premium reformer pilates studio'),
  spec(373, 'surfschool', 'surfcoaching', 'SurfSchool', '🏄', 'Sports & Recreation', 'Surf School & Ocean Lessons', 'Catch your first wave with safe, local instruction', { file: 'lessons', label: 'Lessons' }, ['Certified Coaches', 'Board Included', 'Ocean Safety'], 'Hero pairs ocean excitement with beginner-safe coaching and lesson booking.', 'Lessons page includes beginner, intermediate, kids, private and multi-day camps.', 'Booking collects swimmers, ages, experience, dates, lesson type and accommodation need.', 'surf school lessons ocean board coach beginner camp kids wave safety', 'beginner surfing lesson on beach'),
  spec(374, 'skatepark', 'skateboardingpark', 'SkatePark', '🛹', 'Sports & Recreation', 'Skate Park & Skateboarding Academy', 'A safe place to roll, progress and create', { file: 'sessions', label: 'Sessions' }, ['Designed Obstacles', 'Protective Gear', 'Beginner Coaching'], 'Hero showcases bowls, ramps and street features plus beginner-friendly sessions.', 'Sessions page covers open skate, coaching, kids camps, memberships and events.', 'Registration asks age, level, discipline, session, gear rental and preferred date.', 'skate park skateboarding academy ramps bowl coaching kids gear session', 'skateboarder performing trick at park'),
  spec(375, 'archeryrange', 'archeryacademy', 'ArcheryRange', '🏹', 'Sports & Recreation', 'Archery Range & Coaching', 'Find focus, form and consistency one arrow at a time', { file: 'programs', label: 'Programs' }, ['Supervised Range', 'Equipment Provided', 'Competition Coaching'], 'Hero introduces safe archery experiences, structured learning and group activities.', 'Programs page covers trial shoots, beginner courses, advanced training and events.', 'Booking gathers age, participants, experience, date, program and event purpose.', 'archery range academy coaching bow arrow target beginner competition group activity', 'archer aiming recurve bow at range'),
  spec(376, 'calisthenicspark', 'calisthenicscoaching', 'CalisthenicsPark', '💪', 'Sports & Recreation', 'Calisthenics Park & Bodyweight Coaching', 'Master strength and movement with your own body', { file: 'training', label: 'Training' }, ['Skill Progressions', 'Outdoor Setup', 'Community Sessions'], 'Hero features pull-ups, handstands and progressive coaching in an outdoor community.', 'Training page covers foundations, skills, strength, mobility and group sessions.', 'Trial form captures level, target skills, injuries, availability and preferred batch.', 'calisthenics bodyweight coaching park pull up handstand strength mobility community', 'outdoor calisthenics athlete on bars'),
  spec(377, 'paddlekayak', 'kayakadventures', 'PaddleKayak', '🛶', 'Sports & Recreation', 'Kayaking Tours & Paddle School', 'Explore calm waters and wild routes with local guides', { file: 'trips', label: 'Trips' }, ['Guide Included', 'Safety Equipment', 'Beginner Friendly'], 'Hero sells scenic paddling, guided adventures and easy first-time access.', 'Trips page lists sunrise, mangrove, river, coastal and multi-day options.', 'Booking captures participants, ages, swim confidence, date, route and transport need.', 'kayaking tour paddle school river coastal adventure guide safety equipment trip', 'guided kayaking through scenic waterway'),
  spec(378, 'cueclub', 'billiardsclub', 'CueClub', '🎱', 'Sports & Recreation', 'Billiards & Snooker Club', 'Quality tables, focused play and lively competition', { file: 'tables', label: 'Tables & Rates' }, ['Tournament Tables', 'Hourly Booking', 'Leagues & Events'], 'Hero presents premium tables, social atmosphere and instant slot booking.', 'Tables & Rates covers snooker, pool, memberships, coaching, leagues and private events.', 'Reservation collects game, table count, players, duration, date and event request.', 'billiards snooker pool club cue table hourly booking league tournament coaching', 'premium billiards club table'),
  spec(379, 'paintballzone', 'paintballarena', 'PaintballZone', '🔫', 'Sports & Recreation', 'Paintball Arena & Team Games', 'Tactical outdoor action for groups that want a challenge', { file: 'missions', label: 'Missions' }, ['Protective Gear', 'Game Marshals', 'Group Packages'], 'Hero delivers action imagery, safety confidence and group booking.', 'Missions page describes arenas, scenarios, ammo packages, birthdays and corporate games.', 'Booking asks players, ages, date, package, occasion and food or transport needs.', 'paintball arena tactical game team building birthday corporate outdoor gear', 'paintball team in outdoor arena'),
  spec(380, 'jumppark', 'trampolinepark', 'JumpPark', '🤸', 'Sports & Recreation', 'Trampoline & Indoor Adventure Park', 'Bounce, climb and celebrate in one high-energy space', { file: 'attractions', label: 'Attractions' }, ['Trained Marshals', 'Grip Socks', 'Party Rooms'], 'Hero showcases connected trampolines, obstacle zones and birthday excitement.', 'Attractions page covers free jump, dodgeball, foam pit, ninja course and toddler zones.', 'Booking collects jumpers, ages, date, duration, party package and food selection.', 'trampoline park indoor adventure jump birthday kids ninja foam pit dodgeball', 'colorful indoor trampoline adventure park'),

  spec(381, 'petgroomvan', 'petgroomingvan', 'PetGroomVan', '🚐', 'Animals & Pets', 'Mobile Pet Grooming Van', 'Salon-quality grooming delivered at your doorstep', { file: 'packages', label: 'Packages' }, ['Doorstep Service', 'Sanitized Van', 'Pet-safe Products'], 'Hero shows a fully equipped grooming van and stress-reduced home-area appointments.', 'Packages page covers bath, haircut, de-shedding, nail and puppy services by pet size.', 'Booking captures pet, breed, weight, coat, service, behavior notes and address.', 'mobile pet grooming van dog cat bath haircut doorstep nail deshedding', 'modern mobile dog grooming van'),
  spec(382, 'petfarewell', 'petmemorials', 'PetFarewell', '🕊️', 'Animals & Pets', 'Pet Cremation & Memorial Services', 'Compassionate support for a dignified final goodbye', { file: 'memorials', label: 'Memorial Options' }, ['Respectful Care', 'Pickup Available', 'Memorial Keepsakes'], 'Hero uses gentle language to explain immediate support, respectful care and availability.', 'Memorial Options details private or communal cremation, urns, paw prints and remembrance items.', 'Support request captures pet type, location, timing, pickup need and preferred contact.', 'pet cremation memorial farewell urn paw print pickup compassionate aftercare loss', 'peaceful pet memorial keepsake'),
  spec(383, 'aquabreeder', 'ornamentalfishbreeding', 'AquaBreeder', '🐠', 'Animals & Pets', 'Ornamental Fish Breeder', 'Healthy, responsibly raised fish for aquarists and stores', { file: 'stock', label: 'Available Stock' }, ['Quarantined Stock', 'Species Guidance', 'Safe Packing'], 'Hero presents healthy breeding systems, current stock and nationwide enquiry.', 'Available Stock groups freshwater species, shrimp, breeding pairs and wholesale lots.', 'Order enquiry captures species, quantity, tank experience, city and shipping preference.', 'ornamental fish breeder aquarium freshwater shrimp breeding pair wholesale healthy stock', 'colorful ornamental fish breeding tanks'),
  spec(384, 'petdaycare', 'dogdaycare', 'PetDaycare', '🐕', 'Animals & Pets', 'Dog Daycare & Boarding', 'Safe play, attentive care and comfortable stays', { file: 'stays', label: 'Daycare & Stays' }, ['Supervised Play', 'Daily Updates', 'Clean Sleep Areas'], 'Hero reassures owners with supervised social play, routines and photo updates.', 'Daycare & Stays compares half-day, full-day, overnight and long-stay care.', 'Booking asks dog breed, age, vaccination, temperament, dates, feeding and medication.', 'dog daycare boarding pet stay supervised play overnight vaccination daily updates', 'happy dogs playing at daycare'),
  spec(385, 'mobilevet', 'doorstepveterinary', 'MobileVet', '🩺', 'Animals & Pets', 'Mobile Veterinary Care', 'Professional veterinary visits in the comfort of home', { file: 'care', label: 'Care Services' }, ['Licensed Vets', 'Home Visits', 'Digital Records'], 'Hero offers low-stress home consultations, vaccinations and follow-up support.', 'Care Services covers wellness exams, vaccines, minor treatment, senior care and diagnostics.', 'Appointment captures pet, symptoms, urgency, history, address and preferred time.', 'mobile vet home visit veterinary pet vaccination consultation senior care diagnostics', 'veterinarian examining dog at home'),
  spec(386, 'exoticpets', 'exoticpetcare', 'ExoticPets', '🦎', 'Animals & Pets', 'Exotic Pet Care & Supplies', 'Specialist guidance for reptiles, birds and small exotics', { file: 'species', label: 'Species Care' }, ['Specialist Advice', 'Habitat Supplies', 'Responsible Ownership'], 'Hero establishes knowledgeable, welfare-led support for less-common companion animals.', 'Species Care covers reptiles, birds, rabbits, rodents and habitat essentials.', 'Enquiry asks species, age, care need, habitat setup, city and consultation preference.', 'exotic pet care reptile bird rabbit habitat supplies consultation welfare', 'responsible exotic reptile pet care'),
  spec(387, 'pawsrescue', 'animalrescue', 'PawsRescue', '🐾', 'Animals & Pets', 'Animal Rescue & Adoption', 'Rescue, rehabilitation and loving forever homes', { file: 'adopt', label: 'Adopt' }, ['Verified Adoptions', 'Medical Care', 'Volunteer Network'], 'Hero prioritizes adoptable animals, emergency rescue reporting and donation CTA.', 'Adopt page provides animal profiles, status, temperament and adoption process.', 'Application gathers home, family, pet experience, preferred animal and consent to screening.', 'animal rescue adoption dog cat shelter volunteer donate foster rehabilitation', 'rescued dog ready for adoption'),
  spec(388, 'dogmind', 'caninebehavior', 'DogMind', '🧠', 'Animals & Pets', 'Canine Behavior & Training', 'Kind, practical training for calmer dogs and confident owners', { file: 'training', label: 'Training' }, ['Force-free Methods', 'Home Programs', 'Owner Coaching'], 'Hero addresses pulling, reactivity, fear and puppy foundations without judgment.', 'Training page covers assessments, puppy classes, obedience and behavior modification.', 'Assessment asks breed, age, behavior, triggers, history, goals and session location.', 'dog behavior training puppy obedience reactivity force free canine trainer home', 'positive reinforcement dog training'),
  spec(389, 'aquascapecraft', 'aquascaping', 'AquascapeCraft', '🌿', 'Animals & Pets', 'Aquascaping Design & Installation', 'Living underwater landscapes designed for your space', { file: 'scapes', label: 'Aquascapes' }, ['Custom Layouts', 'Plant Selection', 'Maintenance Plans'], 'Hero showcases planted aquarium transformations and complete setup expertise.', 'Aquascapes page explores nature, iwagumi, jungle and biotope styles with projects.', 'Design brief captures tank size, location, style, livestock, budget and maintenance need.', 'aquascaping planted aquarium design installation aquatic plants tank maintenance layout', 'lush planted aquascape aquarium'),
  spec(390, 'horsecare', 'equinecare', 'HorseCare', '🐴', 'Animals & Pets', 'Equine Care & Stable Services', 'Reliable daily care for healthy, comfortable horses', { file: 'services', label: 'Services' }, ['Experienced Grooms', 'Routine Tracking', 'Emergency Coordination'], 'Hero communicates dependable stable management, grooming and horse-first care.', 'Services page covers boarding, grooming, feeding, exercise, farrier and vet coordination.', 'Enquiry asks horse count, breed, care type, facility, schedule and location.', 'horse care equine stable boarding grooming feeding exercise farrier management', 'horse receiving professional stable care'),
  spec(391, 'catcafelounge', 'catcafe', 'CatCafeLounge', '🐈', 'Animals & Pets', 'Cat Café & Adoption Lounge', 'Coffee, calm company and meaningful feline connections', { file: 'visit', label: 'Plan a Visit' }, ['Resident Cats', 'Timed Sessions', 'Adoption Support'], 'Hero blends cozy café ambience, resident-cat introductions and visit reservations.', 'Plan a Visit explains session rules, menu, events, cat welfare and adoption profiles.', 'Reservation collects guests, date, slot, children, allergies and event interest.', 'cat cafe lounge coffee adoption resident cats reservation welfare events cozy', 'cozy cat cafe interior'),
  spec(392, 'petphotostudio', 'animalphotography', 'PetPhotoStudio', '📸', 'Animals & Pets', 'Pet Photography Studio', 'Joyful portraits that preserve every personality', { file: 'sessions', label: 'Sessions' }, ['Pet-paced Shoots', 'Studio Props', 'Print Packages'], 'Hero features expressive pet portraits and a patient, pet-led shoot experience.', 'Sessions page covers studio, outdoor, birthday, family and memorial photography.', 'Booking asks pet type, number, temperament, session, date, location and print interest.', 'pet photography dog cat portrait studio outdoor session prints birthday family', 'professional joyful dog portrait studio'),
  spec(393, 'aviarycraft', 'aviarydesign', 'AviaryCraft', '🦜', 'Animals & Pets', 'Custom Aviaries & Bird Enclosures', 'Safe, enriching spaces designed around your birds', { file: 'aviaries', label: 'Aviaries' }, ['Species-led Design', 'Weather-safe Build', 'Easy-clean Details'], 'Hero showcases indoor and outdoor enclosures balancing welfare, safety and beauty.', 'Aviaries page covers balcony, garden, breeding and walk-in designs plus materials.', 'Design form gathers species, bird count, space, dimensions, climate and budget.', 'custom aviary bird enclosure cage design outdoor indoor breeding safe build', 'large landscaped walk in aviary'),
  spec(394, 'petphysio', 'animalrehabilitation', 'PetPhysio', '🐕‍🦺', 'Animals & Pets', 'Pet Physiotherapy & Rehabilitation', 'Support mobility, recovery and comfort at every life stage', { file: 'therapy', label: 'Therapies' }, ['Qualified Therapists', 'Recovery Plans', 'Owner Exercises'], 'Hero addresses surgery recovery, arthritis and mobility with compassionate evidence-led care.', 'Therapies page covers assessment, exercise, massage, laser, hydro and senior support.', 'Appointment captures pet, diagnosis, surgery date, mobility issue, referral and location.', 'pet physiotherapy rehabilitation dog mobility arthritis surgery recovery hydrotherapy laser', 'canine physiotherapy rehabilitation session'),
  spec(395, 'dogbakery', 'caninetreats', 'DogBakery', '🦴', 'Animals & Pets', 'Dog Bakery & Celebration Cakes', 'Fresh, dog-safe treats for everyday rewards and big days', { file: 'menu', label: 'Treat Menu' }, ['Pet-safe Ingredients', 'Custom Cakes', 'Allergy Options'], 'Hero features colorful dog cakes, baked treats and celebration ordering.', 'Treat Menu groups biscuits, pupcakes, birthday cakes, gift boxes and dietary options.', 'Order form asks dog name, breed, allergies, product, flavor, message and pickup date.', 'dog bakery pet cake treats biscuits birthday pupcake allergy safe fresh', 'colorful dog birthday cake and treats'),
  spec(396, 'agrovet', 'livestockveterinary', 'AgroVet', '🐄', 'Animals & Pets', 'Livestock Veterinary & Farm Care', 'Practical herd health support for productive farms', { file: 'farmcare', label: 'Farm Care' }, ['Field Visits', 'Herd Programs', 'Farmer Guidance'], 'Hero positions accessible farm calls, prevention and urgent livestock care.', 'Farm Care covers treatment, vaccination, fertility, nutrition, herd checks and biosecurity.', 'Visit request captures species, animal count, symptoms, urgency, village and directions.', 'livestock veterinary farm cattle buffalo goat herd vaccination fertility field visit', 'veterinarian checking cattle on farm'),
  spec(397, 'petrelocate', 'petrelocation', 'PetRelocate', '✈️', 'Animals & Pets', 'Domestic & International Pet Relocation', 'Carefully managed travel from paperwork to reunion', { file: 'journeys', label: 'Relocation Plans' }, ['Document Support', 'IATA Crates', 'Travel Updates'], 'Hero reduces relocation anxiety with coordinated, welfare-first travel management.', 'Relocation Plans explains domestic, international, accompanied and door-to-door services.', 'Assessment asks pet, breed, origin, destination, target date, vaccinations and travel mode.', 'pet relocation international domestic travel import export documents crate flight transport', 'pet travel crate at airport journey'),
  spec(398, 'aquafix', 'aquariummaintenance', 'AquaFix', '🐟', 'Animals & Pets', 'Aquarium Repair & Maintenance', 'Clear water, healthy systems and dependable on-site care', { file: 'maintenance', label: 'Maintenance' }, ['Water Testing', 'Filter Service', 'Emergency Visits'], 'Hero addresses cloudy water, leaks, failing equipment and routine tank care.', 'Maintenance page covers cleaning, water testing, filter repair, setup moves and AMCs.', 'Service request captures tank type, size, issue, livestock, location and photos.', 'aquarium maintenance repair cleaning filter water testing fish tank leak service', 'technician maintaining large aquarium'),
  spec(399, 'dogfashion', 'petapparel', 'DogFashion', '👕', 'Animals & Pets', 'Dog Clothing & Pet Accessories', 'Comfortable fits with personality in every detail', { file: 'shop', label: 'Shop' }, ['Size Guidance', 'Soft Fabrics', 'Custom Names'], 'Hero presents seasonal outfits, occasion wear and practical accessories.', 'Shop page groups clothing, harnesses, bandanas, beds and personalized pieces.', 'Order support captures breed, measurements, item, color, personalization and delivery.', 'dog clothing pet fashion apparel harness bandana accessories custom name size', 'stylish dog wearing fashionable outfit'),
  spec(400, 'petdna', 'animalgenetics', 'PetDNA', '🧬', 'Animals & Pets', 'Pet DNA & Genetic Testing', 'Discover ancestry, traits and inherited health risks', { file: 'tests', label: 'DNA Tests' }, ['At-home Kit', 'Secure Results', 'Expert Guidance'], 'Hero explains simple sample collection and actionable genetic insights for pet owners.', 'DNA Tests compares ancestry, breed, trait and health panels with report timelines.', 'Order page captures pet species, test choice, age, shipping address and vet-sharing consent.', 'pet dna genetic testing ancestry breed health traits at home kit report', 'pet DNA testing kit and dog'),
];
