'use strict';
// Categories 31-100 — structured from user specifications.
module.exports = [
  {
    num: 31, id: 'stonecraft', niche: 'stoneart', name: 'StoneCraft', emoji: '🏛️', group: 'Artisan & Craft',
    title: 'Monument & Stone Art / Sculptors', tagline: 'Handcrafted marble & granite statues, temple carving and custom stone art',
    page2: { file: 'products', label: 'Products' }, usps: ['Handcrafted', 'High Durability', 'PAN India Shipping'],
    p1: 'Marble & granite statues banner. Custom temple & carving work. CTA: "Inquire Custom Marble Art". USPs: Handcrafted, High Durability, PAN India Shipping.',
    p2: 'Category tabs [Religious Idols] [Home Decor] [Temple Pillars]. High-res photo gallery with dimensions & material type.',
    p3: 'Sculptor heritage story. Client testimonials. Custom order inquiry form (marble type select, size, "send design on WhatsApp"). Map location & UPI advance QR.',
    keywords: 'monument stone art sculptor marble granite statue idol temple carving murti', colors: { bg: '#faf7f2', card: '#efe8dc', accent: '#8a6d3b', text: '#2f2a20' }, imgTheme: 'marble statue sculpture stone carving',
  },
  {
    num: 32, id: 'lockmaster', niche: 'locksmith', name: 'LockMaster', emoji: '🔐', group: 'Local Services',
    title: 'Locksmith & Key Makers', tagline: 'Fast lock opening, duplicate keys and smart security solutions',
    page2: { file: 'services', label: 'Services' }, usps: ['24/7 Emergency', 'Damage-Free Opening', 'Verified Locksmiths'],
    p1: 'Emergency locksmith hero for home, office and vehicle lockouts. CTA: "Call Locksmith Now". Show 24/7 response, damage-free opening and verified technicians.',
    p2: 'Service cards for duplicate keys, lock repair, car keys, digital locks and safe opening, with visit charges and starting rates.',
    p3: 'Technician credentials, service-area map and reviews. Booking form asks lock type, location, urgency and photo upload; WhatsApp dispatch and UPI payment QR.',
    keywords: 'locksmith key maker duplicate key tala chabi car lock smart lock emergency', colors: { bg: '#10151d', card: '#1d2632', accent: '#f5b942', text: '#f7f9fc' }, imgTheme: 'locksmith keys digital door lock',
  },
  {
    num: 33, id: 'aquaclean', niche: 'poolcare', name: 'AquaClean', emoji: '🏊', group: 'Home & Facility Services',
    title: 'Swimming Pool Cleaning & Maintenance', tagline: 'Crystal-clear pools with professional cleaning and water balancing',
    page2: { file: 'packages', label: 'Packages' }, usps: ['Water Tested', 'Trained Team', 'AMC Available'],
    p1: 'Sparkling pool before-and-after hero. Residential, society and hotel maintenance. CTA: "Book Pool Inspection". Highlight water testing, trained staff and AMC support.',
    p2: 'One-time cleaning, weekly care and annual maintenance packages. Include skimming, vacuuming, filter service, chlorine/pH balancing and pool-size-based rates.',
    p3: 'Maintenance process, equipment gallery and client reviews. Form asks pool type, dimensions, current water condition and preferred visit date; map, WhatsApp and UPI QR.',
    keywords: 'swimming pool cleaning maintenance chlorine ph filter society hotel pool service', colors: { bg: '#eefcff', card: '#d9f5fa', accent: '#0788a8', text: '#123b47' }, imgTheme: 'clean blue swimming pool maintenance',
  },
  {
    num: 34, id: 'artcanvas', niche: 'artclass', name: 'ArtCanvas', emoji: '🎨', group: 'Education & Creative',
    title: 'Drawing, Painting & Fine Art Classes', tagline: 'Creative art classes for kids, beginners and advanced learners',
    page2: { file: 'courses', label: 'Courses' }, usps: ['Expert Artists', 'Small Batches', 'Materials Guidance'],
    p1: 'Colorful student artwork hero with kids and adult batches. CTA: "Book Free Trial Class". Feature expert artists, small batches and exhibition opportunities.',
    p2: 'Course cards for drawing basics, watercolor, acrylic, sketching, canvas painting and entrance portfolio preparation, with age group, duration and monthly fees.',
    p3: 'Teacher profiles, student gallery, certificates and testimonials. Admission form asks age, skill level, course and batch timing; studio map, WhatsApp and fee UPI QR.',
    keywords: 'art class drawing painting sketching canvas watercolor kids hobby kala classes', colors: { bg: '#fff8f1', card: '#ffe6d5', accent: '#e34f6f', text: '#4b2432' }, imgTheme: 'children painting art class colorful canvas',
  },
  {
    num: 35, id: 'scoopheaven', niche: 'icecream', name: 'ScoopHeaven', emoji: '🍨', group: 'Food & Beverage',
    title: 'Ice Cream Parlour & Dessert Bar', tagline: 'Creamy scoops, sundaes, shakes and celebration desserts',
    page2: { file: 'menu', label: 'Menu' }, usps: ['Freshly Made', 'Eggless Options', 'Party Orders'],
    p1: 'Vibrant ice-cream hero featuring signature scoops, sundaes and shakes. CTA: "Order on WhatsApp". Promote fresh batches, eggless choices and party tubs.',
    p2: 'Filterable menu [Scoops] [Sundaes] [Shakes] [Family Packs] with flavors, sizes, add-ons and prices; highlight seasonal specials and combo offers.',
    p3: 'Brand story, outlet gallery and customer reviews. Custom cake/tub order form asks flavor, quantity, date and message; map, delivery WhatsApp and UPI QR.',
    keywords: 'ice cream parlour gelato kulfi sundae shake dessert scoop party order', colors: { bg: '#fff4fa', card: '#fce1ef', accent: '#d94687', text: '#52213a' }, imgTheme: 'colorful ice cream scoops sundae dessert',
  },
  {
    num: 36, id: 'aquadrop', niche: 'watersupply', name: 'AquaDrop', emoji: '🚰', group: 'Essential Services',
    title: 'Water Tanker & Drinking Water Supply', tagline: 'Reliable drinking and utility water delivered on time',
    page2: { file: 'rates', label: 'Rates' }, usps: ['Tested Water', 'On-Time Delivery', 'Bulk Supply'],
    p1: 'Water tanker delivery hero for homes, societies, construction and events. CTA: "Book a Tanker". Show tested water, quick dispatch and bulk capacity.',
    p2: 'Rate cards by tanker capacity and water type: drinking, borewell/utility and construction water. Include distance charges, subscription plans and emergency delivery rates.',
    p3: 'Water quality proof, fleet photos and customer reviews. Booking form asks liters/tanker size, water type, full address, landmark and delivery time; live-call, WhatsApp and UPI QR.',
    keywords: 'water tanker supply drinking pani delivery society construction bulk jal', colors: { bg: '#edf8ff', card: '#dceeff', accent: '#1677be', text: '#17364d' }, imgTheme: 'water tanker drinking water delivery',
  },
  {
    num: 37, id: 'plywoodpro', niche: 'plywood', name: 'PlyWoodPro', emoji: '🪵', group: 'Building & Interiors',
    title: 'Plywood, Laminate & Veneer Dealer', tagline: 'Trusted plywood, laminates and boards for every interior project',
    page2: { file: 'catalog', label: 'Catalog' }, usps: ['Genuine Brands', 'Wholesale Rates', 'Site Delivery'],
    p1: 'Premium wood-finish hero with plywood, MDF, laminates and veneers. CTA: "Get Material Quote". Display genuine brands, wholesale pricing and site delivery.',
    p2: 'Catalog filters [Plywood] [MDF/HDF] [Laminates] [Veneers] [Hardware]. Show thickness, grade, sheet size, brand, warranty and per-sheet/quote rates.',
    p3: 'Showroom gallery, brand partners and carpenter reviews. Quote form asks material list, thickness, quantity, project location and file upload; map, WhatsApp and UPI advance QR.',
    keywords: 'plywood laminate veneer mdf hdf board sunmica interior carpenter wholesale', colors: { bg: '#f7f1e8', card: '#eadbc8', accent: '#8b572a', text: '#362619' }, imgTheme: 'plywood laminate veneer wood showroom',
  },
  {
    num: 38, id: 'eventsupplies', niche: 'tentrental', name: 'EventSupplies', emoji: '⛺', group: 'Events & Rentals',
    title: 'Tent House & Event Equipment Rental', tagline: 'Tents, seating, stage and event essentials delivered and installed',
    page2: { file: 'catalog', label: 'Rental Catalog' }, usps: ['Complete Setup', 'Clean Inventory', 'On-Time Delivery'],
    p1: 'Grand event setup hero with shamiana, chairs, tables, stage and lighting. CTA: "Get Event Rental Quote". Highlight complete installation and clean inventory.',
    p2: 'Rental catalog for tents, sofa/chairs, tables, crockery, coolers, carpets, stage and barricades. Show per-piece/per-day rates, packages and minimum quantity.',
    p3: 'Past-event gallery, setup process and testimonials. Form asks event type, date, venue, guest count and required items; StadiumConnect link, WhatsApp and UPI advance QR.',
    keywords: 'tent house shamiana chair table rental event saman mandap stage crockery', colors: { bg: '#fff8ed', card: '#f7e6c9', accent: '#b86b17', text: '#422b16' }, imgTheme: 'wedding tent event furniture rental',
  },
  {
    num: 39, id: 'astrovastu', niche: 'astrology', name: 'AstroVastu', emoji: '🔯', group: 'Spiritual & Consulting',
    title: 'Astrologer, Vastu & Kundli Services', tagline: 'Personalized kundli, vastu and life guidance from trusted experts',
    page2: { file: 'services', label: 'Services' }, usps: ['Private Consultation', 'Detailed Reports', 'Online Sessions'],
    p1: 'Celestial astrology hero for kundli, marriage matching, vastu and numerology. CTA: "Book Consultation". Emphasize privacy, experienced guidance and online sessions.',
    p2: 'Services with fixed rates: janam kundli, kundli milan, career/business reading, vastu visit, numerology and muhurat. Explain report format and delivery time.',
    p3: 'Astrologer lineage, credentials and client testimonials. Form asks name, birth date, exact birth time, birthplace and concern; call/WhatsApp consultation and UPI dakshina QR.',
    keywords: 'astrologer astrology vastu kundli jyotish kundali milan numerology muhurat pandit', colors: { bg: '#160f2b', card: '#261b43', accent: '#f2bd59', text: '#fff8e8' }, imgTheme: 'vedic astrology kundli vastu zodiac',
  },
  {
    num: 40, id: 'powerbackup', niche: 'invertershop', name: 'PowerBackup', emoji: '🔋', group: 'Electrical & Energy',
    title: 'Inverter, Battery & UPS Dealer', tagline: 'Reliable backup power for homes, shops and offices',
    page2: { file: 'products', label: 'Products' }, usps: ['Top Brands', 'Installation Included', 'Warranty Support'],
    p1: 'Power-backup hero featuring home inverter, tubular battery and online UPS. CTA: "Find My Backup System". Show brand assurance, installation and warranty service.',
    p2: 'Product filters [Home Inverter] [Battery] [Office UPS] [Solar Combo], with VA/Ah capacity, backup estimate, supported appliances, brands and exchange prices.',
    p3: 'Load calculator, installation photos and reviews. Recommendation form asks appliances, total load, backup hours, current battery and pincode; technician visit, WhatsApp quote and UPI QR.',
    keywords: 'inverter battery ups power backup luminous exide amaron tubular bijli', colors: { bg: '#101827', card: '#1e293b', accent: '#fbbf24', text: '#f8fafc' }, imgTheme: 'home inverter battery ups power backup',
  },
  {
    num: 41, id: 'scrapexpress', niche: 'scrap', name: 'ScrapExpress', emoji: '♻️', group: 'Recycling & Local Services',
    title: 'Scrap Buyer & Kabadi Pickup', tagline: 'Transparent scrap rates with doorstep weighing and instant payment',
    page2: { file: 'rates', label: 'Scrap Rates' }, usps: ['Daily Rates', 'Digital Weighing', 'Doorstep Pickup'],
    p1: 'Doorstep kabadi pickup hero for paper, metal, appliances and office scrap. CTA: "Schedule Pickup". Highlight live rates, digital weighing and instant payment.',
    p2: 'Daily rate board for newspaper, cardboard, iron, steel, copper, aluminium, plastic and e-waste, showing per-kg rates and bulk/commercial terms.',
    p3: 'Recycling process, weighing proof and customer reviews. Pickup form asks scrap category, estimated weight, photos, floor/lift and address; WhatsApp confirmation and UPI settlement.',
    keywords: 'scrap buyer kabadi raddi paper iron copper aluminium ewaste pickup rate', colors: { bg: '#eef8ef', card: '#dcebdc', accent: '#347a3c', text: '#1e3821' }, imgTheme: 'scrap recycling metal paper pickup',
  },
  {
    num: 42, id: 'silkcare', niche: 'embroidery', name: 'SilkCare', emoji: '🪡', group: 'Artisan & Fashion',
    title: 'Embroidery, Zari & Fabric Handwork', tagline: 'Detailed hand embroidery, zari and custom bridal workmanship',
    page2: { file: 'services', label: 'Work Catalog' }, usps: ['Handcrafted Detail', 'Custom Designs', 'Bridal Specialists'],
    p1: 'Rich textile hero showcasing zari, aari, zardozi and bridal blouse work. CTA: "Discuss Custom Design". Promote handcrafted detail and bridal expertise.',
    p2: 'Style gallery [Aari] [Zardozi] [Maggam] [Bead Work] [Machine Embroidery] with per-piece/starting rates, timelines and fabric suitability.',
    p3: 'Karigar story, close-up portfolio and client reviews. Order form asks garment type, fabric, occasion, budget, deadline and design upload; WhatsApp approval and UPI advance QR.',
    keywords: 'embroidery zari zardozi aari maggam bridal blouse handwork karigar kadhai', colors: { bg: '#2a1020', card: '#431b32', accent: '#d8a84e', text: '#fff4e5' }, imgTheme: 'zardozi embroidery bridal fabric handwork',
  },
  {
    num: 43, id: 'framefix', niche: 'windows', name: 'FrameFix', emoji: '🪟', group: 'Building & Interiors',
    title: 'Aluminium, uPVC Windows & Doors', tagline: 'Custom windows, doors and partitions with precise installation',
    page2: { file: 'products', label: 'Products' }, usps: ['Custom Sizes', 'Weather Resistant', 'Professional Fitting'],
    p1: 'Modern window-and-door hero for aluminium and uPVC fabrication. CTA: "Request Site Measurement". Highlight custom sizing, weather resistance and neat fitting.',
    p2: 'Product types [Sliding Windows] [Casement] [Doors] [Partitions] [Mosquito Mesh], showing profile, glass options, colors, hardware and per-sq.ft/quote rates.',
    p3: 'Completed-site gallery, profile brands and warranty details. Form asks opening dimensions, product type, glass choice, quantity and site location; WhatsApp drawings, map and UPI advance QR.',
    keywords: 'aluminium window upvc door sliding partition mosquito mesh fabrication khidki', colors: { bg: '#f1f6f8', card: '#dfe9ed', accent: '#397387', text: '#1c3540' }, imgTheme: 'modern aluminium upvc windows doors',
  },
  {
    num: 44, id: 'freshcut', niche: 'meatshop', name: 'FreshCut', emoji: '🥩', group: 'Food Retail',
    title: 'Fresh Meat, Chicken & Seafood Shop', tagline: 'Hygienically cut fresh meat and seafood delivered to your door',
    page2: { file: 'menu', label: 'Products' }, usps: ['Fresh Daily', 'Hygienic Cutting', 'Home Delivery'],
    p1: 'Clean premium butcher-shop hero featuring chicken, mutton, fish and marinated cuts. CTA: "Order Fresh Cuts". Show daily freshness, hygiene and delivery.',
    p2: 'Product tabs [Chicken] [Mutton] [Fish] [Marinated] with cut options, net weight, per-kg price, cleaning choice and availability badges.',
    p3: 'Sourcing and hygiene process, store photos and reviews. Order form asks product, cut style, quantity, delivery slot and address; WhatsApp order, map and UPI QR.',
    keywords: 'meat shop chicken mutton fish seafood fresh halal cut delivery gosht', colors: { bg: '#fff7f4', card: '#f6e2dc', accent: '#b63b32', text: '#4a211e' }, imgTheme: 'fresh meat chicken seafood butcher shop',
  },
  {
    num: 45, id: 'evdrive', niche: 'evshowroom', name: 'EVDrive', emoji: '🛵', group: 'Mobility & Auto',
    title: 'Electric Scooter & EV Showroom', tagline: 'Smart electric mobility with test rides, finance and service support',
    page2: { file: 'models', label: 'Models' }, usps: ['Low Running Cost', 'Finance Available', 'Test Rides'],
    p1: 'Futuristic electric scooter hero with range and savings message. CTA: "Book Test Ride". Highlight low running cost, easy finance and local service.',
    p2: 'Model comparison cards with ex-showroom price, certified range, top speed, battery, charging time, colors, subsidy and EMI; compare up to three EVs.',
    p3: 'Savings calculator, showroom gallery and owner reviews. Test-ride form asks model, name, phone, city and preferred date; map, WhatsApp and booking UPI QR.',
    keywords: 'electric scooter ev bike showroom battery range test ride emi subsidy', colors: { bg: '#071a20', card: '#102d34', accent: '#4ade80', text: '#ecfff4' }, imgTheme: 'electric scooter ev showroom charging',
  },
  {
    num: 46, id: 'soundstudio', niche: 'musicshop', name: 'SoundStudio', emoji: '🎸', group: 'Music & Creative',
    title: 'Musical Instruments & Recording Gear', tagline: 'Instruments, studio gear and expert setup for every musician',
    page2: { file: 'catalog', label: 'Catalog' }, usps: ['Genuine Brands', 'Expert Guidance', 'Demo Available'],
    p1: 'Energetic music-store hero with guitars, keyboards, drums and microphones. CTA: "Book a Product Demo". Feature genuine gear, expert help and repairs.',
    p2: 'Catalog filters [Guitars] [Keyboards] [Drums] [Studio] [Accessories], with brand, model, specifications, stock, price and rental/finance options.',
    p3: 'Demo room gallery, artist testimonials and brand partners. Enquiry form asks instrument, experience level, budget and demo date; store map, WhatsApp and UPI QR.',
    keywords: 'music shop guitar keyboard drums microphone studio instruments tabla harmonium', colors: { bg: '#111018', card: '#24202e', accent: '#a78bfa', text: '#faf7ff' }, imgTheme: 'musical instruments guitar keyboard recording studio',
  },
  {
    num: 47, id: 'spinwash', niche: 'laundry', name: 'SpinWash', emoji: '🧺', group: 'Home Services',
    title: 'Laundry, Dry Cleaning & Ironing', tagline: 'Fresh, carefully cleaned clothes with doorstep pickup and delivery',
    page2: { file: 'rates', label: 'Rate Card' }, usps: ['Doorstep Pickup', 'Fabric-Safe Care', 'On-Time Delivery'],
    p1: 'Fresh laundry hero offering wash-fold, steam iron and dry cleaning. CTA: "Schedule Pickup". Show fabric-safe processes, doorstep service and express delivery.',
    p2: 'Rate card tabs [Wash & Fold] [Ironing] [Dry Clean] [Household] with per-kg/per-piece rates, minimum order, express surcharge and subscription plans.',
    p3: 'Cleaning process, stain policy and reviews. Pickup form asks service, item count/weight, stain notes, address and time slot; order tracking link, WhatsApp and UPI QR.',
    keywords: 'laundry dry clean ironing press wash fold kapde doorstep pickup dhobi', colors: { bg: '#eef8ff', card: '#dbeeff', accent: '#286fbe', text: '#173654' }, imgTheme: 'laundry dry cleaning folded clothes',
  },
  {
    num: 48, id: 'copyquick', niche: 'xerox', name: 'CopyQuick', emoji: '📄', group: 'Office & Printing',
    title: 'Xerox, Scanning & Document Centre', tagline: 'Fast copies, prints, scans and document services under one roof',
    page2: { file: 'rates', label: 'Rates' }, usps: ['Quick Service', 'Bulk Discounts', 'WhatsApp Files'],
    p1: 'Busy document-center hero for Xerox, color print, scan, lamination and binding. CTA: "Send File on WhatsApp". Highlight speed and student/bulk rates.',
    p2: 'Rate list for B&W/color copies, A4/A3 printing, scanning, lamination, spiral binding, photo print and online forms, with per-page and bulk slabs.',
    p3: 'Machine setup, sample work and customer reviews. Order form asks service, paper size, copies, color/duplex and file upload; map, WhatsApp delivery and UPI QR.',
    keywords: 'xerox photocopy print scan lamination binding online form document center', colors: { bg: '#f4f7fb', card: '#e3eaf3', accent: '#245aa8', text: '#1d304d' }, imgTheme: 'photocopy printing scanning document shop',
  },
  {
    num: 49, id: 'pureorganics', niche: 'organiccosmetics', name: 'PureOrganics', emoji: '🌿', group: 'Beauty & Wellness',
    title: 'Organic Cosmetics & Herbal Skincare', tagline: 'Plant-based skincare and haircare made for everyday wellness',
    page2: { file: 'products', label: 'Products' }, usps: ['Natural Ingredients', 'Cruelty Free', 'Skin-Type Guidance'],
    p1: 'Botanical beauty hero with face, hair and body essentials. CTA: "Shop Natural Care". Emphasize ingredient transparency, cruelty-free products and consultations.',
    p2: 'Product filters [Face] [Hair] [Body] [Gift Sets], showing ingredients, skin type, benefits, size, usage and price; include combo savings and bestseller badges.',
    p3: 'Founder and sourcing story, ingredient glossary and reviews. Consultation/order form asks skin/hair concern, allergies, products and address; WhatsApp guidance and UPI QR.',
    keywords: 'organic cosmetics herbal skincare natural beauty ayurvedic haircare face serum', colors: { bg: '#f5f7ec', card: '#e6ead5', accent: '#667c3e', text: '#2e3922' }, imgTheme: 'organic skincare herbal cosmetics botanical',
  },
  {
    num: 50, id: 'medequip', niche: 'medequip', name: 'MedEquip', emoji: '🩼', group: 'Healthcare & B2B',
    title: 'Medical Equipment Sales & Rental', tagline: 'Certified medical equipment for home care, clinics and hospitals',
    page2: { file: 'catalog', label: 'Equipment' }, usps: ['Certified Products', 'Rental Available', 'Setup Support'],
    p1: 'Trust-focused medical equipment hero with hospital bed, oxygen concentrator and wheelchair. CTA: "Request Equipment". Promote certified products and home setup.',
    p2: 'Catalog [Respiratory] [Mobility] [Beds] [Monitoring] [Surgical], with specifications, purchase/rental rates, deposit, availability and delivery coverage.',
    p3: 'Brand certifications, installation process and caregiver reviews. Requirement form asks patient need, equipment, rent/buy, duration, prescription upload and address; urgent call, WhatsApp and UPI QR.',
    keywords: 'medical equipment hospital bed oxygen concentrator wheelchair rental patient care', colors: { bg: '#eff9f8', card: '#dbeeed', accent: '#167f79', text: '#183d3a' }, imgTheme: 'medical equipment hospital bed wheelchair oxygen',
  },
  {
    num: 51, id: 'earthmovers', niche: 'earthmovers', name: 'EarthMovers', emoji: '🚜', group: 'Building & Real Estate',
    title: 'JCB, Crane & Heavy Earthmover Rental', tagline: 'Heavy machines with trained operators for construction and excavation',
    page2: { file: 'fleet', label: 'Fleet' }, usps: ['Trained Operators', 'Hourly & Shift Rates', 'Site Ready'],
    p1: 'Action hero with JCB, excavator, crane and loader at work. CTA: "Book a Machine". Highlight trained operators, maintained fleet and rapid site mobilization.',
    p2: 'Fleet cards for JCB/backhoe, excavator, poclain, hydra crane, loader and dumper, showing capacity, attachments and hourly/8-hour shift rates.',
    p3: 'Project gallery, safety records and contractor reviews. Booking form asks machine, work type, site location, required hours/days and start date; WhatsApp dispatch and UPI advance QR.',
    keywords: 'jcb rental crane excavator poclain earthmover loader hydra construction bhade', colors: { bg: '#171714', card: '#292821', accent: '#f3b719', text: '#fffbea' }, imgTheme: 'JCB excavator crane construction machinery',
  },
  {
    num: 52, id: 'borewellpro', niche: 'borewell', name: 'BoreWellPro', emoji: '🕳️', group: 'Building & Real Estate',
    title: 'Borewell Drilling & Pump Installation', tagline: 'Survey-led borewell drilling, casing and pump setup',
    page2: { file: 'services', label: 'Services' }, usps: ['Site Survey', 'Modern Rig', 'Complete Installation'],
    p1: 'Borewell rig hero for residential, farm and industrial drilling. CTA: "Request Site Survey". Highlight experienced crew, modern rigs and complete pump setup.',
    p2: 'Services for geological survey, drilling, casing, flushing, submersible pump installation and old-bore cleaning, with per-foot and material-based rates.',
    p3: 'Rig gallery, drilling process and client reviews. Form asks land type, location, expected depth, bore diameter and access width; map pin, WhatsApp quote and UPI advance QR.',
    keywords: 'borewell drilling boring tube well submersible pump casing per foot pani', colors: { bg: '#f5f1e8', card: '#e6ddca', accent: '#8b642f', text: '#392d1d' }, imgTheme: 'borewell drilling rig submersible pump',
  },
  {
    num: 53, id: 'aquaseal', niche: 'waterproofing', name: 'AquaSeal', emoji: '🛡️', group: 'Building & Real Estate',
    title: 'Waterproofing & Leakage Repair', tagline: 'Long-lasting terrace, bathroom and wall leakage solutions',
    page2: { file: 'services', label: 'Solutions' }, usps: ['Leak Diagnosis', 'Warranty Options', 'Site Inspection'],
    p1: 'Before-and-after leakage hero for terraces, bathrooms, tanks and walls. CTA: "Book Leak Inspection". Feature diagnosis, branded chemicals and warranty.',
    p2: 'Solution cards for terrace coating, bathroom treatment, injection grouting, basement, water tank and exterior wall, with per-sq.ft/estimate rates.',
    p3: 'Application process, warranty terms and project photos. Inspection form asks leakage area, property type, approximate size, age and photo upload; WhatsApp inspection and UPI advance QR.',
    keywords: 'waterproofing leakage repair terrace bathroom seepage grouting dampness chhat', colors: { bg: '#eef8fb', card: '#d9edf2', accent: '#16748b', text: '#173d47' }, imgTheme: 'terrace waterproofing leakage repair',
  },
  {
    num: 54, id: 'glassedge', niche: 'glassrailing', name: 'GlassEdge', emoji: '🏢', group: 'Building & Real Estate',
    title: 'Glass Railing, Facade & Toughened Glass', tagline: 'Premium glass fabrication for balconies, offices and storefronts',
    page2: { file: 'products', label: 'Solutions' }, usps: ['Toughened Safety Glass', 'Custom Fabrication', 'Precision Fitting'],
    p1: 'Architectural glass hero with balcony railing, office partition and facade. CTA: "Get Site Quote". Highlight safety glass and precise custom installation.',
    p2: 'Product gallery [Railings] [Partitions] [Shower Enclosures] [Facades] [Shopfronts], showing glass thickness, hardware, finish and per-sq.ft/quote rates.',
    p3: 'Completed projects, hardware brands and warranty. Form asks application, dimensions, glass type, railing style and site address; drawing upload, WhatsApp and UPI advance QR.',
    keywords: 'glass railing toughened glass balcony partition facade shower cubicle fabrication', colors: { bg: '#f4f9fc', card: '#e1edf4', accent: '#347a9d', text: '#19394a' }, imgTheme: 'modern glass railing facade partition',
  },
  {
    num: 55, id: 'mixcrete', niche: 'rmc', name: 'MixCrete', emoji: '🚛', group: 'Building & Real Estate',
    title: 'Ready-Mix Concrete Supplier', tagline: 'Quality-controlled RMC delivered for residential and commercial projects',
    page2: { file: 'grades', label: 'Concrete Grades' }, usps: ['Quality Tested', 'Timed Delivery', 'Pump Available'],
    p1: 'RMC transit-mixer hero for slabs, foundations and infrastructure. CTA: "Request Concrete Quote". Show lab-tested mix, scheduled delivery and pumping support.',
    p2: 'Concrete grades M10 through M40 and custom design mixes, with application, slump, minimum cubic-meter order, per-m³ rate and pump/transport charges.',
    p3: 'Plant and lab gallery, quality certificates and contractor reviews. Order form asks grade, quantity in m³, pour date/time, site access and pump requirement; WhatsApp coordination and UPI advance QR.',
    keywords: 'ready mix concrete rmc cement M20 M25 transit mixer pump construction', colors: { bg: '#f2f2f0', card: '#deded9', accent: '#d05b28', text: '#302d2a' }, imgTheme: 'ready mix concrete truck construction pour',
  },
  {
    num: 56, id: 'scaffoldpro', niche: 'scaffolding', name: 'ScaffoldPro', emoji: '🏗️', group: 'Building & Real Estate',
    title: 'Scaffolding & Shuttering Rental', tagline: 'Safe scaffolding, centering and shuttering material on rent',
    page2: { file: 'catalog', label: 'Rental Catalog' }, usps: ['Safety Checked', 'Flexible Rental', 'Site Delivery'],
    p1: 'High-rise scaffolding hero showing safe erection and material supply. CTA: "Get Rental Estimate". Highlight tested inventory, site delivery and erection teams.',
    p2: 'Rental catalog for cuplock, H-frame, props, spans, plates, pipes and clamps with sizes, per-piece/day or monthly rates, deposits and minimum quantities.',
    p3: 'Safety checklist, inventory yard and project reviews. Form asks project height/area, system, quantity, rental period and delivery site; BOQ upload, WhatsApp and UPI advance QR.',
    keywords: 'scaffolding shuttering centering cuplock props plates rental construction bhada', colors: { bg: '#1b2025', card: '#2c333a', accent: '#f59e0b', text: '#f8fafc' }, imgTheme: 'construction scaffolding shuttering equipment',
  },
  {
    num: 57, id: 'balloonmagic', niche: 'balloondecor', name: 'BalloonMagic', emoji: '🎈', group: 'Artisan, Decor & Event',
    title: 'Balloon Decoration & Party Styling', tagline: 'Creative balloon decor for birthdays, welcomes and celebrations',
    page2: { file: 'packages', label: 'Packages' }, usps: ['Custom Themes', 'On-Time Setup', 'Photo-Ready Decor'],
    p1: 'Joyful party hero with balloon arches, backdrops and themed setups. CTA: "Choose a Decor Package". Feature custom colors and same-day setup options.',
    p2: 'Packages for birthday, baby shower, anniversary, welcome baby and corporate events, with inclusions, setup time, add-ons and starting prices.',
    p3: 'Theme gallery, decorator story and reviews. Booking form asks event, date/time, venue, theme/colors, budget and reference upload; StadiumConnect link, WhatsApp and UPI advance QR.',
    keywords: 'balloon decoration birthday decor arch backdrop baby shower party decorator', colors: { bg: '#fff6fb', card: '#fce3f1', accent: '#e84d9b', text: '#50203b' }, imgTheme: 'colorful balloon party decoration arch',
  },
  {
    num: 58, id: 'bloomcraft', niche: 'flowershop', name: 'BloomCraft', emoji: '💐', group: 'Artisan, Decor & Event',
    title: 'Florist, Bouquets & Floral Decor', tagline: 'Fresh bouquets and floral styling for every meaningful moment',
    page2: { file: 'catalog', label: 'Flowers' }, usps: ['Fresh Flowers', 'Custom Bouquets', 'Same-Day Delivery'],
    p1: 'Elegant flower hero featuring bouquets, wedding varmala and event arrangements. CTA: "Order Flowers". Highlight freshness, custom messages and same-day delivery.',
    p2: 'Catalog [Bouquets] [Varmala] [Car Decor] [Event Florals] [Corporate], with flower types, sizes, price, delivery slots and seasonal availability.',
    p3: 'Florist story, arrangement gallery and customer reviews. Order form asks occasion, flowers/colors, budget, delivery date/address and card message; WhatsApp and UPI QR.',
    keywords: 'flower shop florist bouquet phool varmala wedding floral decor delivery', colors: { bg: '#f8f4f4', card: '#eadfde', accent: '#9b4f68', text: '#3f2830' }, imgTheme: 'fresh flower bouquet wedding floral decor',
  },
  {
    num: 59, id: 'frameart', niche: 'framing', name: 'FrameArt', emoji: '🖼️', group: 'Artisan, Decor & Event',
    title: 'Photo Framing & Custom Frames', tagline: 'Custom photo, artwork and certificate framing with fine finishes',
    page2: { file: 'catalog', label: 'Frame Catalog' }, usps: ['Custom Sizes', 'Premium Finishes', 'Careful Mounting'],
    p1: 'Gallery-wall hero with photo, canvas, certificate and memorabilia frames. CTA: "Design My Frame". Highlight custom sizes and preservation mounting.',
    p2: 'Frame styles [Classic Wood] [Modern] [Metal] [Shadow Box] [Canvas], with molding, color, glass, mount options and per-foot/size rates.',
    p3: 'Workshop story, finished-work gallery and reviews. Quote form asks item type, dimensions, frame style, glass and image upload; pickup/delivery, WhatsApp proof and UPI QR.',
    keywords: 'photo frame custom framing artwork certificate canvas shadow box frame shop', colors: { bg: '#f7f3eb', card: '#e8dfd0', accent: '#815c38', text: '#35291f' }, imgTheme: 'custom picture frames gallery wall workshop',
  },
  {
    num: 60, id: 'soundproofpro', niche: 'acoustics', name: 'SoundProofPro', emoji: '🔇', group: 'Artisan, Decor & Event',
    title: 'Acoustic Treatment & Soundproofing', tagline: 'Engineered acoustic solutions for studios, offices and auditoriums',
    page2: { file: 'solutions', label: 'Solutions' }, usps: ['Acoustic Analysis', 'Custom Design', 'Measured Results'],
    p1: 'Premium studio acoustic hero with panels, bass traps and insulated rooms. CTA: "Book Acoustic Assessment". Feature measurement-led design and installation.',
    p2: 'Solutions for recording studios, home theatres, offices, restaurants and auditoriums, with material options, NRC values and per-sq.ft/project rates.',
    p3: 'Before-after measurements, project gallery and client reviews. Form asks room use, dimensions, noise issue, budget and plan upload; site visit, WhatsApp and UPI advance QR.',
    keywords: 'acoustic soundproofing studio panels noise control home theatre auditorium insulation', colors: { bg: '#111318', card: '#22262d', accent: '#e05b45', text: '#f6f2ee' }, imgTheme: 'acoustic panels recording studio soundproof room',
  },
  {
    num: 61, id: 'heritagehub', niche: 'antiques', name: 'HeritageHub', emoji: '🏺', group: 'Artisan, Decor & Event',
    title: 'Antiques & Vintage Collectibles', tagline: 'Curated vintage objects, heritage decor and collectible treasures',
    page2: { file: 'collection', label: 'Collection' }, usps: ['Curated Pieces', 'Provenance Details', 'Secure Shipping'],
    p1: 'Museum-inspired hero featuring clocks, brassware, furniture and vintage collectibles. CTA: "Explore Collection". Emphasize curation, provenance and secure packing.',
    p2: 'Collection filters [Furniture] [Brass] [Clocks] [Art] [Collectibles], with era, origin, condition, dimensions, authenticity notes and price-on-request.',
    p3: 'Collector story, restoration notes and buyer testimonials. Enquiry form asks item, delivery city and offer/question; valuation form supports photos, history and dimensions, plus WhatsApp and UPI advance QR.',
    keywords: 'antiques vintage collectibles heritage decor brass old coins furniture purana saman', colors: { bg: '#201912', card: '#33281d', accent: '#c39757', text: '#f4ead8' }, imgTheme: 'antique vintage collectibles brass furniture',
  },
  {
    num: 62, id: 'matchmilan', niche: 'matrimony', name: 'MatchMilan', emoji: '💞', group: 'Artisan, Decor & Event',
    title: 'Matrimonial & Matchmaking Service', tagline: 'Trusted, private and personalized matchmaking for families',
    page2: { file: 'plans', label: 'Membership Plans' }, usps: ['Verified Profiles', 'Private Service', 'Personal Matchmaker'],
    p1: 'Warm trust-led matrimony hero for serious family-assisted matches. CTA: "Register Profile". Highlight verified profiles, privacy and personal matchmaking.',
    p2: 'Membership plans Basic, Assisted and Premium with duration, profile introductions, horoscope matching and relationship-manager support; show exact/starting fees.',
    p3: 'Success stories, verification process and privacy policy. Registration form asks name, age, community, education, profession, city, preferences and photo/biodata upload; confidential WhatsApp and UPI QR.',
    keywords: 'matrimony matchmaking marriage vivah shaadi biodata kundli verified profiles rishta', colors: { bg: '#fff4f1', card: '#f8ded7', accent: '#b74652', text: '#4b2529' }, imgTheme: 'Indian matrimony wedding couple family',
  },
  {
    num: 63, id: 'selfdrive', niche: 'selfdrive', name: 'SelfDrive', emoji: '🚙', group: 'Mobility & Logistics',
    title: 'Self-Drive Car Rental', tagline: 'Clean, flexible rental cars for city drives and road trips',
    page2: { file: 'fleet', label: 'Cars' }, usps: ['Sanitized Cars', 'Flexible Kilometers', 'Roadside Support'],
    p1: 'Road-trip car hero with hatchback, sedan and SUV rentals. CTA: "Check Car Availability". Show clean vehicles, flexible plans and support.',
    p2: 'Fleet filters by car type, seats and transmission, showing hourly/daily rates, kilometer limits, security deposit, fuel policy and availability.',
    p3: 'Rental steps, vehicle gallery and renter reviews. Booking form asks pickup/return date-time, location, car, driver age and license upload; WhatsApp confirmation and UPI deposit QR.',
    keywords: 'self drive car rental rent gaadi hatchback sedan suv road trip booking', colors: { bg: '#eef4f7', card: '#dce7ed', accent: '#23647d', text: '#173645' }, imgTheme: 'self drive rental car road trip',
  },
  {
    num: 64, id: 'temporide', niche: 'tempotravel', name: 'TempoRide', emoji: '🚐', group: 'Mobility & Logistics',
    title: 'Tempo Traveller & Group Tour Rental', tagline: 'Comfortable group travel with experienced drivers and clear pricing',
    page2: { file: 'fleet', label: 'Fleet' }, usps: ['Experienced Drivers', 'Clean Vehicles', 'All-India Trips'],
    p1: 'Group-travel hero with luxury tempo travellers and minibuses. CTA: "Get Trip Fare". Feature clean seating, professional drivers and outstation service.',
    p2: 'Fleet cards for 9, 12, 17 and 20-seater vehicles with AC, pushback seats, luggage, per-km/day rates, driver allowance, toll and minimum billing.',
    p3: 'Vehicle interiors, trip routes and reviews. Quote form asks pickup, destinations, dates, passengers, vehicle and itinerary; WhatsApp fare, map and UPI advance QR.',
    keywords: 'tempo traveller rental minibus group tour outstation yatra per km gaadi', colors: { bg: '#fff8e9', card: '#f6e7c6', accent: '#c47b18', text: '#432e13' }, imgTheme: 'tempo traveller minibus group tour',
  },
  {
    num: 65, id: 'chargepoint', niche: 'evcharging', name: 'ChargePoint', emoji: '⚡', group: 'Mobility & Logistics',
    title: 'EV Charging Station & Charger Installation', tagline: 'Fast public charging and smart chargers for home or business',
    page2: { file: 'chargers', label: 'Chargers' }, usps: ['Fast Charging', 'Multi-Brand Support', 'Installation Service'],
    p1: 'Electric vehicle charging hero with live station and home charger. CTA: "Find / Install a Charger". Show connector support and uptime.',
    p2: 'Charger options AC 3.3/7.2/22kW and DC fast charging, with connector, charge time, compatibility, unit/session rates and installation pricing.',
    p3: 'Station map, installation projects and reviews. Form asks vehicle model, home/commercial site, sanctioned load, parking distance and pincode; site survey, WhatsApp and UPI QR.',
    keywords: 'ev charging station charger installation electric car bike fast charge CCS', colors: { bg: '#081b1a', card: '#12302e', accent: '#52e28b', text: '#effff5' }, imgTheme: 'electric vehicle charging station home charger',
  },
  {
    num: 66, id: 'motofix', niche: 'bikerepair', name: 'MotoFix', emoji: '🏍️', group: 'Mobility & Logistics',
    title: 'Bike Repair & Two-Wheeler Service', tagline: 'Reliable bike servicing, repairs and doorstep pickup',
    page2: { file: 'services', label: 'Services' }, usps: ['Trained Mechanics', 'Clear Estimates', 'Pickup Available'],
    p1: 'Workshop hero featuring motorcycle service and repair. CTA: "Book Bike Service". Highlight trained mechanics, genuine parts and pickup.',
    p2: 'Service cards for periodic service, engine repair, brakes, clutch, tyres, battery and washing, with bike-type starting rates and labor/parts notes.',
    p3: 'Mechanic profiles, workshop gallery and reviews. Booking form asks bike brand/model, kilometers, issue, pickup address and date; estimate approval on WhatsApp and UPI QR.',
    keywords: 'bike repair motorcycle service mechanic garage puncture engine two wheeler pickup', colors: { bg: '#171717', card: '#292929', accent: '#ef5a32', text: '#fafafa' }, imgTheme: 'motorcycle repair mechanic workshop',
  },
  {
    num: 67, id: 'freightlink', niche: 'freight', name: 'FreightLink', emoji: '🚚', group: 'Mobility & Logistics',
    title: 'Freight Transport & Truck Booking', tagline: 'Reliable part-load and full-truck transport across India',
    page2: { file: 'fleet', label: 'Fleet & Rates' }, usps: ['PAN India Network', 'GPS Updates', 'Insured Options'],
    p1: 'Highway logistics hero with trucks and goods movement. CTA: "Get Freight Quote". Highlight PAN-India routes, tracking and full/part loads.',
    p2: 'Vehicle options pickup, Tata Ace, 14/17/19-ft truck, container and trailer, with load capacity, route-based rates and FTL/PTL terms.',
    p3: 'Route network, fleet gallery and client reviews. Quote form asks pickup/drop, goods type, weight, dimensions, vehicle and date; e-way bill notes, WhatsApp tracking and UPI advance QR.',
    keywords: 'freight transport truck booking logistics goods carrier part load FTL tempo', colors: { bg: '#eef3f6', card: '#dce5ea', accent: '#315d72', text: '#1b3541' }, imgTheme: 'freight trucks highway logistics transport',
  },
  {
    num: 68, id: 'heavydrive', niche: 'heavydriving', name: 'HeavyDrive', emoji: '🚌', group: 'Mobility & Logistics',
    title: 'Heavy Vehicle Driving School', tagline: 'Professional truck, bus and commercial driving training',
    page2: { file: 'courses', label: 'Courses' }, usps: ['Experienced Trainers', 'Practical Training', 'License Guidance'],
    p1: 'Commercial driving hero with truck and bus training. CTA: "Join Heavy Driving Course". Promote practical road training and RTO guidance.',
    p2: 'Courses for transport license, truck, bus, trailer and refresher training, with eligibility, duration, practical hours, vehicle provided and fees.',
    p3: 'Training ground, instructor credentials and student reviews. Admission form asks age, current license class/number, course, preferred batch and ID upload; map, WhatsApp and fee UPI QR.',
    keywords: 'heavy driving school truck bus trailer commercial license transport training RTO', colors: { bg: '#f5f4ec', card: '#e7e4d5', accent: '#9a6a20', text: '#3c321e' }, imgTheme: 'truck bus driving school training',
  },
  {
    num: 69, id: 'securevision', niche: 'cctv', name: 'SecureVision', emoji: '📹', group: 'Tech, Office & B2B',
    title: 'CCTV & Surveillance Systems', tagline: 'Smart camera security for homes, shops and commercial sites',
    page2: { file: 'packages', label: 'Packages' }, usps: ['Remote Viewing', 'Professional Wiring', 'AMC Support'],
    p1: 'Security monitoring hero with CCTV cameras and mobile viewing. CTA: "Book Free Site Survey". Show HD recording, remote access and installation.',
    p2: '2/4/8/16-camera packages with analog/IP cameras, DVR/NVR, storage days, night vision, wiring allowance, brands and installed prices.',
    p3: 'Installation gallery, brand partners and reviews. Survey form asks property type, indoor/outdoor camera count, recording days and location; floor-plan upload, WhatsApp and UPI advance QR.',
    keywords: 'cctv camera surveillance security dvr nvr night vision installation shop home', colors: { bg: '#0d1724', card: '#1b2a3c', accent: '#39a9ff', text: '#f0f8ff' }, imgTheme: 'CCTV security camera surveillance control room',
  },
  {
    num: 70, id: 'firesafe', niche: 'firesafety', name: 'FireSafe', emoji: '🧯', group: 'Tech, Office & B2B',
    title: 'Fire Safety Equipment & Compliance', tagline: 'Certified fire protection systems, refilling and safety audits',
    page2: { file: 'products', label: 'Products' }, usps: ['Certified Equipment', 'Compliance Support', 'AMC Available'],
    p1: 'Fire-protection hero with extinguishers, alarms and hydrants. CTA: "Request Fire Audit". Highlight certified equipment and compliance support.',
    p2: 'Products/services for ABC/CO₂ extinguishers, refilling, alarms, sprinklers, hydrants, signage and PPE, with capacity, standards and unit/AMC rates.',
    p3: 'Licenses, installation gallery and corporate clients. Audit form asks building type, floors, area, occupancy and existing systems; compliance document upload, WhatsApp and UPI QR.',
    keywords: 'fire safety extinguisher refill alarm hydrant sprinkler audit compliance AMC', colors: { bg: '#fff3ef', card: '#f8ddd5', accent: '#c43d2f', text: '#4a211d' }, imgTheme: 'fire extinguisher safety alarm hydrant',
  },
  {
    num: 71, id: 'kitchenpro', niche: 'kitchenequip', name: 'KitchenPro', emoji: '👨‍🍳', group: 'Tech, Office & B2B',
    title: 'Commercial Kitchen Equipment', tagline: 'Stainless-steel kitchen equipment for hotels, restaurants and caterers',
    page2: { file: 'catalog', label: 'Equipment' }, usps: ['Food-Grade Steel', 'Custom Fabrication', 'Installation Support'],
    p1: 'Professional kitchen hero with ranges, refrigeration and stainless workstations. CTA: "Plan My Kitchen". Show food-grade fabrication and turnkey setup.',
    p2: 'Catalog [Cooking] [Preparation] [Refrigeration] [Washing] [Display], with capacity, dimensions, power/fuel, steel grade and price/quote.',
    p3: 'Factory and installed-kitchen gallery, brand clients and warranty. Form asks business type, covers/day, space, equipment list and floor-plan upload; site visit, WhatsApp and UPI advance QR.',
    keywords: 'commercial kitchen equipment hotel restaurant catering stainless steel oven freezer', colors: { bg: '#f1f4f5', card: '#dfe5e8', accent: '#526b78', text: '#26363e' }, imgTheme: 'commercial restaurant kitchen stainless equipment',
  },
  {
    num: 72, id: 'weighright', niche: 'weighbridge', name: 'WeighRight', emoji: '⚖️', group: 'Tech, Office & B2B',
    title: 'Weighbridge & Industrial Weighing', tagline: 'Accurate weighbridges, scales and calibration support',
    page2: { file: 'products', label: 'Products' }, usps: ['Certified Accuracy', 'Installation Included', 'Calibration Support'],
    p1: 'Industrial weighing hero with truck weighbridge and digital scale. CTA: "Get Weighing Solution". Highlight accuracy, civil guidance and calibration.',
    p2: 'Products for pit/pitless weighbridges, platform scales, crane scales and load cells, with capacity, platform size, indicator/software and quote pricing.',
    p3: 'Installed sites, certificates and client reviews. Form asks industry, maximum load, platform size, pit preference, site and software need; drawing upload, WhatsApp and UPI advance QR.',
    keywords: 'weighbridge weighing scale dharam kanta load cell calibration truck scale', colors: { bg: '#edf2f4', card: '#dbe3e7', accent: '#456879', text: '#223842' }, imgTheme: 'truck weighbridge industrial weighing scale',
  },
  {
    num: 73, id: 'solarflow', niche: 'solarpump', name: 'SolarFlow', emoji: '☀️', group: 'Tech, Office & B2B',
    title: 'Solar Water Pump Systems', tagline: 'Efficient solar pumping for farms, borewells and remote water supply',
    page2: { file: 'systems', label: 'Pump Systems' }, usps: ['Low Running Cost', 'Subsidy Guidance', 'Site Survey'],
    p1: 'Sunny farm hero with solar panels powering irrigation pump. CTA: "Calculate Pump Requirement". Feature no-fuel operation and subsidy guidance.',
    p2: 'DC/AC surface and submersible systems by 1–10 HP, showing head, discharge, panel wattage, bore depth, controller and installed/estimate price.',
    p3: 'Savings calculator, installations and farmer reviews. Survey form asks water source, depth/head, daily water need, crop area, current pump and village; WhatsApp and UPI advance QR.',
    keywords: 'solar pump water agriculture submersible irrigation subsidy kisan borewell panel', colors: { bg: '#fffbea', card: '#f5ebbd', accent: '#d69a0f', text: '#433616' }, imgTheme: 'solar water pump farm irrigation panels',
  },
  {
    num: 74, id: 'billingpro', niche: 'pos', name: 'BillingPro', emoji: '🧾', group: 'Tech, Office & B2B',
    title: 'POS Billing Software & Machines', tagline: 'Fast billing, inventory and GST tools for modern businesses',
    page2: { file: 'plans', label: 'Plans' }, usps: ['GST Ready', 'Inventory Sync', 'Training Included'],
    p1: 'Modern retail counter hero with POS terminal, barcode and receipt printer. CTA: "Book Free Demo". Show GST billing and inventory control.',
    p2: 'Plans for retail, restaurant and multi-store POS, plus hardware bundles, with users, outlets, cloud backup, integrations, monthly/yearly fees and setup cost.',
    p3: 'Product tour, compatible hardware and merchant reviews. Demo form asks business type, outlets, devices, monthly bills and required features; remote/on-site demo, WhatsApp and UPI QR.',
    keywords: 'pos billing software GST inventory barcode printer restaurant retail dukaan', colors: { bg: '#f1f4ff', card: '#dfe5fb', accent: '#4a57c8', text: '#252d62' }, imgTheme: 'POS billing terminal retail counter software',
  },
  {
    num: 75, id: 'pureflow', niche: 'rocare', name: 'PureFlow', emoji: '💧', group: 'Home Services',
    title: 'RO Water Purifier Service', tagline: 'Purifier repair, filter replacement and AMC at your doorstep',
    page2: { file: 'services', label: 'Services' }, usps: ['Multi-Brand Service', 'TDS Testing', 'Genuine Filters'],
    p1: 'Clean-water hero with RO purifier service technician. CTA: "Book RO Service". Promote multi-brand repairs, TDS testing and genuine filters.',
    p2: 'Service rates for inspection, filter/membrane replacement, leakage, pump/SMPS repair, installation and AMC, with labor and parts shown separately.',
    p3: 'Service process, supported brands and reviews. Booking form asks purifier brand/model, issue, last service, TDS if known, address and slot; WhatsApp technician and UPI QR.',
    keywords: 'ro service water purifier repair filter membrane TDS AMC aquaguard kent', colors: { bg: '#eefaff', card: '#d9f1f8', accent: '#1385a5', text: '#163d49' }, imgTheme: 'RO water purifier service technician',
  },
  {
    num: 76, id: 'sofacare', niche: 'sofarepair', name: 'SofaCare', emoji: '🛋️', group: 'Home Services',
    title: 'Sofa Repair & Upholstery', tagline: 'Restore sofas with new foam, fabric and expert craftsmanship',
    page2: { file: 'services', label: 'Services' }, usps: ['Doorstep Estimate', 'Fabric Choices', 'Skilled Karigars'],
    p1: 'Before-and-after sofa restoration hero. CTA: "Get Sofa Repair Estimate". Highlight foam replacement, upholstery and frame repairs.',
    p2: 'Services for fabric change, foam, spring, recliner mechanism, polishing and custom sofas, with per-seat/foot starting rates and fabric grades.',
    p3: 'Fabric gallery, workshop process and reviews. Estimate form asks sofa type, seats, repair need, preferred fabric, location and photo upload; home visit, WhatsApp and UPI advance QR.',
    keywords: 'sofa repair upholstery fabric foam spring recliner polish karigar furniture', colors: { bg: '#f7f2ec', card: '#e9ddd0', accent: '#8b5d3b', text: '#38291f' }, imgTheme: 'sofa upholstery repair fabric workshop',
  },
  {
    num: 77, id: 'chimneyfix', niche: 'chimneyrepair', name: 'ChimneyFix', emoji: '🧑‍🔧', group: 'Home Services',
    title: 'Kitchen Chimney & Hob Service', tagline: 'Deep cleaning, repair and installation for chimneys and hobs',
    page2: { file: 'services', label: 'Services' }, usps: ['Multi-Brand Experts', 'Deep Cleaning', 'Warranty on Repair'],
    p1: 'Modern kitchen hero with chimney deep-cleaning service. CTA: "Book Chimney Service". Feature multi-brand technicians and transparent parts.',
    p2: 'Rates for inspection, deep cleaning, motor/PCB repair, filter replacement, duct work, hob repair and installation, with labor/parts notes.',
    p3: 'Cleaning process, brand coverage and reviews. Booking form asks brand/model, chimney type, issue, last cleaning, address and slot; photo upload, WhatsApp and UPI QR.',
    keywords: 'chimney repair kitchen cleaning hob service motor filter duct installation', colors: { bg: '#f3f5f6', card: '#e2e6e8', accent: '#596d77', text: '#2b393f' }, imgTheme: 'kitchen chimney cleaning repair service',
  },
  {
    num: 78, id: 'shadecraft', niche: 'awning', name: 'ShadeCraft', emoji: '⛱️', group: 'Home Services',
    title: 'Awning, Canopy & Outdoor Shades', tagline: 'Custom weatherproof shades for shops, balconies and outdoor spaces',
    page2: { file: 'products', label: 'Shade Options' }, usps: ['Custom Measurement', 'Weatherproof Fabric', 'Installation Included'],
    p1: 'Outdoor shade hero with retractable awnings and entrance canopies. CTA: "Request Measurement". Highlight custom fabrication and weatherproof materials.',
    p2: 'Products [Fixed Awning] [Retractable] [Canopy] [Car Parking] [Tensile], with frame, fabric, operation, colors and per-sq.ft/quote rates.',
    p3: 'Installed-site gallery, fabric swatches and reviews. Form asks application, width/projection, manual/motorized, color and site photos/address; measurement visit, WhatsApp and UPI advance QR.',
    keywords: 'awning canopy shade retractable balcony shop chajja tensile parking shed', colors: { bg: '#fff8eb', card: '#f2e6c9', accent: '#ba7927', text: '#453117' }, imgTheme: 'retractable awning outdoor canopy shade',
  },
  {
    num: 79, id: 'septiccare', niche: 'septic', name: 'SepticCare', emoji: '🚛', group: 'Home Services',
    title: 'Septic Tank Cleaning & Suction', tagline: 'Safe septic cleaning with vacuum equipment and quick response',
    page2: { file: 'services', label: 'Services' }, usps: ['Vacuum Machine', 'Safety Gear', 'Emergency Service'],
    p1: 'Professional sanitation hero with vacuum tanker and safety crew. CTA: "Book Emergency Cleaning". Show hygienic handling and quick response.',
    p2: 'Services for septic tank, grease trap, sewer line, sludge removal and jetting, with tanker capacity, visit/minimum rates and distance charges.',
    p3: 'Safety process, fleet photos and reviews. Booking form asks property type, tank size, last cleaning, access, urgency and location pin; immediate call/WhatsApp and UPI QR.',
    keywords: 'septic tank cleaning suction vacuum tanker sewer safai gutter sludge', colors: { bg: '#f1f5ef', card: '#dfe8dc', accent: '#527b48', text: '#273b23' }, imgTheme: 'septic tank vacuum cleaning truck',
  },
  {
    num: 80, id: 'smartlock', niche: 'smartlocks', name: 'SmartLock', emoji: '🔒', group: 'Home Services',
    title: 'Smart Door Lock Installation', tagline: 'Keyless fingerprint, PIN and app-controlled security for every door',
    page2: { file: 'products', label: 'Smart Locks' }, usps: ['Door Compatibility Check', 'Expert Installation', 'Warranty Support'],
    p1: 'Premium keyless-entry hero showing fingerprint and app access. CTA: "Check My Door". Highlight secure installation and setup training.',
    p2: 'Smart lock catalog with fingerprint, PIN, RFID, Wi-Fi and hotel locks, showing door type/thickness, access methods, battery, emergency key and installed price.',
    p3: 'Installation gallery, supported doors and reviews. Form asks door material, thickness, existing lock, access needs and photo upload; video/site check, WhatsApp and UPI advance QR.',
    keywords: 'smart lock digital door fingerprint pin RFID wifi installation security tala', colors: { bg: '#111820', card: '#202b36', accent: '#42c4d8', text: '#effcff' }, imgTheme: 'smart digital fingerprint door lock',
  },
  {
    num: 81, id: 'fightfit', niche: 'martialarts', name: 'FightFit', emoji: '🥋', group: 'Education & Sports',
    title: 'Martial Arts & Self-Defence Academy', tagline: 'Disciplined training in karate, taekwondo and practical self-defence',
    page2: { file: 'courses', label: 'Programs' }, usps: ['Certified Coaches', 'Kids & Adults', 'Trial Class'],
    p1: 'High-energy dojo hero with karate and self-defence training. CTA: "Book Trial Class". Highlight certified coaches and belt progression.',
    p2: 'Programs for kids karate, taekwondo, kickboxing, women self-defence and competition training, with age, schedule, uniform and monthly fees.',
    p3: 'Coach credentials, tournament gallery and student reviews. Admission form asks age, experience, program, batch and medical note; academy map, WhatsApp and fee UPI QR.',
    keywords: 'martial arts karate taekwondo kickboxing self defence academy dojo classes', colors: { bg: '#171313', card: '#2b2222', accent: '#e5483f', text: '#fff7f5' }, imgTheme: 'karate martial arts dojo training',
  },
  {
    num: 82, id: 'skatezone', niche: 'skating', name: 'SkateZone', emoji: '🛼', group: 'Education & Sports',
    title: 'Roller Skating Academy', tagline: 'Fun, safe skating lessons from beginner to competitive level',
    page2: { file: 'courses', label: 'Courses' }, usps: ['Safety First', 'Certified Coaches', 'Competition Training'],
    p1: 'Dynamic rink hero with children learning roller skating. CTA: "Join a Trial Session". Feature safety gear and progressive coaching.',
    p2: 'Courses for beginner balance, speed skating, inline, artistic and competition batches, with age, level, schedule, equipment needs and fees.',
    p3: 'Coach profiles, medals and student gallery. Registration asks age, current level, skate type/availability, batch and health note; rink map, WhatsApp and UPI QR.',
    keywords: 'skating academy roller inline speed skating kids coaching rink classes', colors: { bg: '#f2f5ff', card: '#dfe6fb', accent: '#5267d8', text: '#263164' }, imgTheme: 'kids roller skating rink coaching',
  },
  {
    num: 83, id: 'braincount', niche: 'abacus', name: 'BrainCount', emoji: '🧮', group: 'Education & Sports',
    title: 'Abacus & Mental Math Classes', tagline: 'Build calculation speed, focus and confidence through abacus learning',
    page2: { file: 'courses', label: 'Levels' }, usps: ['Age-Based Levels', 'Certified Trainers', 'Progress Reports'],
    p1: 'Bright learning hero with children using abacus. CTA: "Book Free Assessment". Highlight mental math, concentration and small batches.',
    p2: 'Level-wise abacus and Vedic maths programs with age eligibility, course duration, weekly classes, kit inclusion and term fees.',
    p3: 'Trainer profiles, competition achievements and parent reviews. Admission form asks child age/class, current ability, center/online preference and batch; WhatsApp and fee UPI QR.',
    keywords: 'abacus mental maths vedic math kids brain development calculation classes', colors: { bg: '#fff9e8', card: '#f5e8bd', accent: '#e58a24', text: '#4a3516' }, imgTheme: 'children abacus mental math class',
  },
  {
    num: 84, id: 'aquacoach', niche: 'swimcoach', name: 'AquaCoach', emoji: '🏊‍♂️', group: 'Education & Sports',
    title: 'Swimming Coach & Learn-to-Swim', tagline: 'Safe, structured swimming lessons for kids and adults',
    page2: { file: 'courses', label: 'Programs' }, usps: ['Certified Coaches', 'Safety Focused', 'All Skill Levels'],
    p1: 'Pool-action hero with coached swimming lesson. CTA: "Book Swim Assessment". Feature beginner confidence, technique and safety.',
    p2: 'Programs for water comfort, beginner, stroke correction, kids, adults and competitive training, with batch size, pool location, sessions and fees.',
    p3: 'Coach certifications, pool safety and learner reviews. Registration asks age, skill, fear/medical note, preferred pool and timing; map, WhatsApp and fee UPI QR.',
    keywords: 'swimming coach classes learn swim kids adults pool training stroke instructor', colors: { bg: '#edfaff', card: '#d6eff8', accent: '#087da5', text: '#123b4c' }, imgTheme: 'swimming coach lesson pool training',
  },
  {
    num: 85, id: 'targetpro', niche: 'shootingrange', name: 'TargetPro', emoji: '🎯', group: 'Education & Sports',
    title: 'Shooting Range & Rifle Training', tagline: 'Safe professional air-rifle and pistol training for sport shooters',
    page2: { file: 'courses', label: 'Training' }, usps: ['Certified Instructors', 'Safety Protocols', 'Equipment Available'],
    p1: 'Focused indoor range hero with sport air-rifle shooter. CTA: "Book Range Session". Stress supervision, safety and competition coaching.',
    p2: 'Options for trial session, beginner air rifle/pistol, membership and competition coaching, with pellets, equipment rental, session time and fees.',
    p3: 'Instructor credentials, range rules and athlete achievements. Booking asks age, experience, discipline, session and ID details; waiver note, map, WhatsApp and UPI QR.',
    keywords: 'shooting range rifle pistol air gun training sports shooter academy nishana', colors: { bg: '#141916', card: '#252d28', accent: '#b7d34b', text: '#f4f8ed' }, imgTheme: 'indoor shooting range air rifle sport',
  },
  {
    num: 86, id: 'dairyfresh', niche: 'dairy', name: 'DairyFresh', emoji: '🐄', group: 'Agriculture & Livestock',
    title: 'Dairy Farm & Fresh Milk Delivery', tagline: 'Farm-fresh milk and dairy products delivered daily',
    page2: { file: 'products', label: 'Products' }, usps: ['Farm Fresh', 'Quality Tested', 'Daily Delivery'],
    p1: 'Pastoral dairy hero with cows and fresh milk. CTA: "Start Milk Subscription". Highlight hygienic milking, testing and doorstep delivery.',
    p2: 'Products for cow/buffalo milk, curd, paneer, ghee and buttermilk with fat details, pack size, daily price and weekly/monthly subscription.',
    p3: 'Farm story, quality reports and subscriber reviews. Subscription form asks product, quantity/day, start date, address and delivery slot; WhatsApp pause/resume and UPI QR.',
    keywords: 'dairy farm fresh milk doodh delivery cow buffalo ghee paneer subscription', colors: { bg: '#f7fbef', card: '#e8f0d8', accent: '#6c8a3a', text: '#31401f' }, imgTheme: 'dairy farm cows fresh milk delivery',
  },
  {
    num: 87, id: 'poultrypro', niche: 'poultrytech', name: 'PoultryPro', emoji: '🐓', group: 'Agriculture & Livestock',
    title: 'Poultry Equipment & Farm Automation', tagline: 'Efficient feeding, drinking and climate systems for poultry farms',
    page2: { file: 'products', label: 'Equipment' }, usps: ['Farm-Sized Design', 'Installation Support', 'Spare Parts'],
    p1: 'Modern poultry shed hero with automated feeding and climate control. CTA: "Plan My Poultry Setup". Highlight scalable systems and service.',
    p2: 'Equipment for feeders, nipple drinkers, brooders, cages, fans, cooling pads and controllers, with bird capacity, specifications and unit/project rates.',
    p3: 'Installed farms, product videos and farmer reviews. Form asks broiler/layer, bird capacity, shed dimensions, new/upgrade and location; layout upload, WhatsApp and UPI advance QR.',
    keywords: 'poultry equipment farm automation feeder drinker cage brooder cooling chicken', colors: { bg: '#fff8e9', card: '#f2e5c8', accent: '#b87828', text: '#463116' }, imgTheme: 'modern poultry farm feeding equipment',
  },
  {
    num: 88, id: 'ecocompost', niche: 'compost', name: 'EcoCompost', emoji: '🌱', group: 'Agriculture & Livestock',
    title: 'Organic Compost & Waste Solutions', tagline: 'Nutrient-rich compost and practical organic waste management',
    page2: { file: 'products', label: 'Products' }, usps: ['Organic Inputs', 'Bulk Supply', 'Usage Guidance'],
    p1: 'Earthy compost hero with healthy soil and plants. CTA: "Order Compost". Promote tested organic inputs, bulk supply and advisory.',
    p2: 'Products for vermicompost, city compost, cocopeat, potting mix, bio-enzyme and composters, with composition, pack size, dosage and retail/bulk rates.',
    p3: 'Composting process, lab reports and grower reviews. Order/advisory form asks crop/garden area, product, quantity, soil concern and delivery location; WhatsApp and UPI QR.',
    keywords: 'organic compost vermicompost khaad cocopeat potting mix waste composter fertilizer', colors: { bg: '#f2f7e9', card: '#dfe9ca', accent: '#5e7c32', text: '#2b3b1b' }, imgTheme: 'organic compost soil vermicompost garden',
  },
  {
    num: 89, id: 'goatcare', niche: 'goatfarm', name: 'GoatCare', emoji: '🐐', group: 'Agriculture & Livestock',
    title: 'Goat Farm & Breeding Stock', tagline: 'Healthy breeds, farm guidance and transparent livestock selection',
    page2: { file: 'livestock', label: 'Livestock' }, usps: ['Healthy Stock', 'Breed Guidance', 'Farm Support'],
    p1: 'Farm hero with healthy goats and breeding setup. CTA: "Enquire Available Stock". Highlight vaccination records and selection guidance.',
    p2: 'Breed cards for Boer, Sirohi, Jamunapari, Barbari and local stock, showing age, weight, purpose, vaccination, live-weight/per-animal rate and availability.',
    p3: 'Farm practices, parent-stock gallery and buyer reviews. Enquiry asks breed, quantity, purpose, budget and delivery city; farm visit, transport guidance, WhatsApp and UPI advance QR.',
    keywords: 'goat farm bakri palan breeding Boer Sirohi Jamunapari livestock sale', colors: { bg: '#f8f3e9', card: '#e9dfcd', accent: '#8a6839', text: '#3a2e1f' }, imgTheme: 'goat farm breeding livestock healthy goats',
  },
  {
    num: 90, id: 'dripgrow', niche: 'dripirrigation', name: 'DripGrow', emoji: '🌾', group: 'Agriculture & Livestock',
    title: 'Drip Irrigation & Farm Water Systems', tagline: 'Water-saving irrigation designed for crop, land and budget',
    page2: { file: 'systems', label: 'Systems' }, usps: ['Farm Survey', 'Subsidy Guidance', 'Installation Support'],
    p1: 'Green farm hero with drip lines and fertigation. CTA: "Book Farm Survey". Highlight water savings, crop-specific planning and subsidy help.',
    p2: 'Systems for drip, sprinkler, rain gun, filtration and fertigation, with acreage kits, spacing, pressure, brand and per-acre/estimate pricing.',
    p3: 'Layout examples, installations and farmer reviews. Survey form asks crop, acreage, water source, pump HP, row spacing and village; land-map upload, WhatsApp and UPI advance QR.',
    keywords: 'drip irrigation sprinkler rain gun farm water subsidy kisan sinchai fertigation', colors: { bg: '#eff8ec', card: '#dcebd6', accent: '#438048', text: '#243b25' }, imgTheme: 'drip irrigation green farm water system',
  },
  {
    num: 91, id: 'timecare', niche: 'watchrepair', name: 'TimeCare', emoji: '⌚', group: 'Specialized & Luxury',
    title: 'Watch Repair & Restoration', tagline: 'Precision servicing for everyday, vintage and luxury watches',
    page2: { file: 'services', label: 'Services' }, usps: ['Skilled Watchmaker', 'Genuine Parts', 'Careful Handling'],
    p1: 'Luxury workbench hero with mechanical watch servicing. CTA: "Request Watch Diagnosis". Show precision tools and careful handling.',
    p2: 'Services for battery, strap, glass, movement repair, water-resistance testing, polishing and vintage restoration, with starting/inspection rates and turnaround.',
    p3: 'Watchmaker heritage, restoration gallery and reviews. Form asks brand/model, movement, issue, last service and photo upload; insured pickup option, WhatsApp quote and UPI advance QR.',
    keywords: 'watch repair clock service battery strap glass luxury vintage ghadi', colors: { bg: '#121212', card: '#24211d', accent: '#c8a86b', text: '#f8f2e7' }, imgTheme: 'luxury watch repair watchmaker tools',
  },
  {
    num: 92, id: 'leatherlux', niche: 'leathercare', name: 'LeatherLux', emoji: '👜', group: 'Specialized & Luxury',
    title: 'Leather Bag, Shoe & Sofa Restoration', tagline: 'Specialist cleaning, recoloring and repair for fine leather goods',
    page2: { file: 'services', label: 'Services' }, usps: ['Color Matching', 'Premium Products', 'Pickup Available'],
    p1: 'Premium leather restoration hero with bags, shoes and sofas. CTA: "Get Restoration Quote". Feature cleaning, recoloring and craftsmanship.',
    p2: 'Services for deep clean, conditioning, scratch/crack repair, recoloring, stitching and hardware, with item-based starting rates and finish options.',
    p3: 'Before-after gallery, care process and luxury-client reviews. Form asks item/brand, leather type, issue, color and photos; pickup city/address, WhatsApp approval and UPI advance QR.',
    keywords: 'leather repair bag shoe sofa restoration cleaning recolor polish luxury', colors: { bg: '#211710', card: '#38271c', accent: '#c68b52', text: '#f9eddf' }, imgTheme: 'luxury leather bag shoe restoration',
  },
  {
    num: 93, id: 'coinheritage', niche: 'coins', name: 'CoinHeritage', emoji: '🪙', group: 'Specialized & Luxury',
    title: 'Rare Coins, Notes & Numismatics', tagline: 'Curated collectible coins and expert numismatic guidance',
    page2: { file: 'collection', label: 'Collection' }, usps: ['Authenticity Notes', 'Collector Guidance', 'Secure Shipping'],
    p1: 'Collector-table hero with historic coins and banknotes. CTA: "Explore Rare Collection". Emphasize condition grading and authenticity details.',
    p2: 'Collection filters [Ancient] [Princely States] [British India] [Republic India] [Notes], with year, mint, denomination, grade, rarity and price.',
    p3: 'Numismatist story, grading guide and buyer reviews. Buy/valuation form asks item, year/mint, condition, provenance and clear photo upload; insured shipping, WhatsApp and UPI advance QR.',
    keywords: 'rare coins old notes numismatics collectible sikka currency antique valuation', colors: { bg: '#161712', card: '#29291f', accent: '#c5a84b', text: '#fbf7df' }, imgTheme: 'rare antique coins banknotes collection',
  },
  {
    num: 94, id: 'aquadecor', niche: 'fountains', name: 'AquaDecor', emoji: '⛲', group: 'Specialized & Luxury',
    title: 'Decorative Fountains & Water Features', tagline: 'Custom indoor and outdoor water features with complete installation',
    page2: { file: 'designs', label: 'Designs' }, usps: ['Custom Design', 'Complete Installation', 'AMC Support'],
    p1: 'Luxury landscape hero with musical, wall and garden fountains. CTA: "Design My Fountain". Highlight custom engineering and lighting.',
    p2: 'Designs [Garden] [Wall] [Indoor] [Musical] [Commercial] with dimensions, material, nozzle/lighting options, pump and project/starting prices.',
    p3: 'Installed-project gallery, design process and reviews. Form asks location, available area, indoor/outdoor, style, budget and site photos; visit booking, WhatsApp and UPI advance QR.',
    keywords: 'fountain water feature garden musical wall indoor landscape decor installation', colors: { bg: '#edf9fa', card: '#d8eef0', accent: '#248a91', text: '#173f42' }, imgTheme: 'luxury decorative fountain water feature',
  },
  {
    num: 95, id: 'skycharter', niche: 'helicopter', name: 'SkyCharter', emoji: '🚁', group: 'Specialized & Luxury',
    title: 'Helicopter Charter & Aerial Services', tagline: 'Private charters, wedding entries and aerial operations with expert coordination',
    page2: { file: 'services', label: 'Services' }, usps: ['Licensed Operators', 'End-to-End Permissions', 'Private Coordination'],
    p1: 'Cinematic helicopter hero for private charter, pilgrimage and wedding entry. CTA: "Request Charter". Stress licensed operations and permissions.',
    p2: 'Services for point-to-point charter, joyride, flower shower, wedding entry, survey and filming, with aircraft capacity, operating requirements and quote/hourly rates.',
    p3: 'Aircraft gallery, safety credentials and client reviews. Enquiry asks service, route/location, date/time, passengers, occasion and landing-site details; private WhatsApp concierge and UPI/bank advance.',
    keywords: 'helicopter charter hire wedding entry joyride aerial survey flower shower private', colors: { bg: '#0b1524', card: '#19283b', accent: '#c9a45e', text: '#f7f3eb' }, imgTheme: 'luxury helicopter charter aerial flight',
  },
  {
    num: 96, id: 'yachtescape', niche: 'yacht', name: 'YachtEscape', emoji: '🛥️', group: 'Specialized & Luxury',
    title: 'Yacht & Luxury Boat Charter', tagline: 'Private cruises and celebrations on premium yachts',
    page2: { file: 'fleet', label: 'Yachts' }, usps: ['Private Charters', 'Crew Included', 'Event Packages'],
    p1: 'Ocean-luxury hero with private yacht at sunset. CTA: "Plan My Yacht Experience". Feature trained crew and celebration packages.',
    p2: 'Fleet cards for speedboats, sailing yachts and luxury cruisers, with guest capacity, duration, route, inclusions, food/decor add-ons and hourly/package rates.',
    p3: 'Onboard gallery, safety details and guest reviews. Booking form asks city/marina, date, guests, occasion, duration and add-ons; ID policy, WhatsApp concierge and UPI advance QR.',
    keywords: 'yacht rental boat charter luxury cruise party private sailing Mumbai Goa', colors: { bg: '#071b2b', card: '#102d42', accent: '#4cc9d8', text: '#effcff' }, imgTheme: 'luxury yacht charter sunset ocean',
  },
  {
    num: 97, id: 'linenpro', niche: 'linensupply', name: 'LinenPro', emoji: '🛏️', group: 'Specialized & Luxury',
    title: 'Hotel Linen Supply & Laundry', tagline: 'Commercial-grade linen supply, rental and laundry for hospitality',
    page2: { file: 'catalog', label: 'Linen Catalog' }, usps: ['Hotel-Grade Quality', 'Bulk Pricing', 'Scheduled Supply'],
    p1: 'Crisp hospitality hero with hotel bedding, towels and table linen. CTA: "Request Bulk Quote". Highlight quality control and recurring supply.',
    p2: 'Catalog [Bed Linen] [Bath] [Restaurant] [Banquet] [Uniforms], with fabric/GSM, size, thread count, MOQ, purchase/rental and laundry rates.',
    p3: 'Laundry facility, hotel clients and quality process. B2B form asks property type, rooms/covers, items, quantity, frequency and sample request; WhatsApp procurement and UPI/bank advance.',
    keywords: 'hotel linen supplier bedsheet towel laundry rental hospitality banquet uniform bulk', colors: { bg: '#f5f8fa', card: '#e4ebef', accent: '#52778a', text: '#263e49' }, imgTheme: 'hotel linen bedding towels hospitality',
  },
  {
    num: 98, id: 'neonglow', niche: 'neonsign', name: 'NeonGlow', emoji: '🌈', group: 'Specialized & Luxury',
    title: 'Custom Neon Signs & LED Boards', tagline: 'Made-to-order neon signs for brands, homes and celebrations',
    page2: { file: 'gallery', label: 'Design Gallery' }, usps: ['Custom Design', 'Low-Power LED', 'PAN India Shipping'],
    p1: 'Dark neon hero with glowing business logo and custom text sign. CTA: "Design My Neon". Promote mockup approval and nationwide shipping.',
    p2: 'Gallery filters [Business] [Wedding] [Home] [Logo] [Rental], with size, color, backing shape, indoor/outdoor, power and per-foot/design price.',
    p3: 'Workshop process, glowing installations and reviews. Quote form asks text/logo, dimensions, colors, backing, deadline and artwork upload; WhatsApp mockup approval and UPI advance QR.',
    keywords: 'neon sign LED board custom name logo wedding decor glow light signage', colors: { bg: '#10091d', card: '#25133b', accent: '#ff45c8', text: '#fff1fc' }, imgTheme: 'custom neon LED sign glowing logo',
  },
  {
    num: 99, id: 'coolpanel', niche: 'pufpanel', name: 'CoolPanel', emoji: '❄️', group: 'Specialized & Luxury',
    title: 'PUF Panels & Cold Room Solutions', tagline: 'Insulated panels and turnkey cold rooms for reliable temperature control',
    page2: { file: 'products', label: 'Products' }, usps: ['Thermal Efficiency', 'Custom Engineering', 'Turnkey Installation'],
    p1: 'Industrial cold-room hero with insulated PUF panels. CTA: "Plan My Cold Room". Highlight thermal performance and turnkey commissioning.',
    p2: 'Products for wall/roof PUF panels, cold rooms, clean rooms and insulated doors, with thickness, density, skin material, temperature and per-sq.m/project rates.',
    p3: 'Factory tests, installed projects and B2B clients. Form asks application, dimensions, target temperature, product load, site and drawing upload; engineering call, WhatsApp and UPI/bank advance.',
    keywords: 'puf panel cold room insulation sandwich panel clean room chiller warehouse', colors: { bg: '#eef5f8', card: '#dce9ef', accent: '#28799b', text: '#183b4a' }, imgTheme: 'PUF insulated panels cold storage room',
  },
  {
    num: 100, id: 'guardforce', niche: 'security', name: 'GuardForce', emoji: '🛡️', group: 'Specialized & Luxury',
    title: 'Security Guard & Facility Protection', tagline: 'Trained guards and professional security management for every site',
    page2: { file: 'services', label: 'Security Services' }, usps: ['Verified Personnel', 'Trained Guards', '24/7 Supervision'],
    p1: 'Commanding security hero with uniformed guards at corporate and residential sites. CTA: "Request Security Assessment". Highlight verification, training and supervision.',
    p2: 'Services for residential, corporate, industrial, event, bouncer, armed guard and housekeeping support, with 8/12-hour shifts, guard count and monthly/quote rates.',
    p3: 'Licenses, training standards, deployment process and client reviews. Requirement form asks site type, location, posts, shifts, guard type and start date; emergency contact, WhatsApp and UPI/bank advance.',
    keywords: 'security guard agency bouncer armed guard society corporate industrial chowkidar', colors: { bg: '#101823', card: '#1d2a38', accent: '#d4a94f', text: '#f7f3e9' }, imgTheme: 'professional security guards corporate facility',
  },
];
